### ISSUE TITLE
Can't read inputdata for RRTMGP runs on titan

### ISSUE THREAD

**Issue by crjones-amath** [E3SM-Project/E3SM#2565] opened 2018-10-04 17:18 UTC
E3SM run on titan using the RRTMGP radiation option (specified by adding '-rad rrtmpg' to CAM_CONFIG_OPTS) fails during initialization with an error while loading necessary input files:

load_and_init(): can't open file /lustre/atlas1/cli900/world-shared/cesm/inputdata/atm/cam/rad/rrtmgp_coefficients_sw_c180724.nc

The files exists, so there must be something else going on (file permissions? netcdf version issues?)

**Comment by brhillman** [comment] 2018-10-04 17:20
I am pretty sure this is a netcdf issue. The RRTMGP input files are netcdf-4, and it looks like a lot of the other input files are netcdf classic. @ndkeen this looks similar to the problem you encountered on NERSC that was solved with updates to the machine config?

**Comment by brhillman** [comment] 2018-10-04 18:05
@PeterCaldwell so the fix is probably to convert these to netCDF3, upload to the E3SM inputdata server, and submit a PR to change the input file names to point to the new netCDF3 files?

**Comment by PeterCaldwell** [comment] 2018-10-04 18:08
I'd start by using nccopy to change the particular file causing the error to netcdf3 format and explicitly specifying its location in user_nl_cam to check that it solves the problem. If it does, your plan sounds like the right way to go.

**Comment by brhillman** [comment] 2018-10-04 18:20
@PeterCaldwell okay thanks. I'll do these things in parallel, since the input files need to be updated regardless. Good to know we can't handle netCDF4.

**Comment by rljacob** [comment] 2018-10-04 18:27
The real problem is the netCDF4-parallel library is broken on some machines, like Titan, so we set Pnetcdf as the default.  But that then doesn't work for input files that are in the NetCDF4 format.  Another workaround is to set PIO_TYPENAME to "netcdf" which will tell the model to use the serial NetCDF4 library which does work on Titan.

@brhillman are you volunteering to do the conversion?  There will be an IG task for that.

**Comment by brhillman** [comment] 2018-10-04 18:31
@rljacob for these two files, yes. I need to update these input files anyways, so it will be more of a replacement of these with updated coefficients, and I will make sure to upload them in netCDF3. Since we don't have an RRTMGP test yet, this will be a BFB change, but will change RRTMGP answers.

**Comment by brhillman** [comment] 2018-11-12 23:36
@amametjanov let's continue iterating on this issue here. Are you building with threads on Anvil/Theta? I'm running some tests now on Edison with this branch to see if I can get the same failure there.

**Comment by amametjanov** [comment] 2018-11-13 00:49
No multi-threading, just pure-MPI. To get a similar environment on Edison, remove hdf5-parallel modules in env_mach_specific.xml:
```
        <command name="load">cray-netcdf/4.4.1.1.6</command>
        <!--command name="load">cray-netcdf-hdf5parallel/4.4.1.1.6</command>
        <command name="load">cray-hdf5-parallel/1.10.1.1</command-->
```

**Comment by brhillman** [comment] 2018-11-13 15:08
@amametjanov okay great thanks, I'll see if I can debug this on Edison.

**Comment by brhillman** [comment] 2018-11-14 17:29
@amametjanov just to follow up I think I see what the problem is and I'm working on a fix to be implemented on the update branch I directed you to. I will let you know when that's ready.

**Comment by brhillman** [comment] 2018-11-15 18:07
@amametjanov could you please pull changes from this branch and try again? It is working for me on Edison now.

**Comment by amametjanov** [comment] 2018-11-15 21:53
```
azamat@edison03:/global/cscratch1/sd/azamat/acme_scratch/edison/ERS_Ld5.ne4_ne4.FC5AV1C-L.edison_intel.20181115_130418_e7x17d/run> grep -ir "^ 1:" e3sm.log.11397199.181115-134157
 1:  Setting mpi info: romio_ds_read=disable
 1:  Setting mpi info: romio_ds_write=disable
 1:  Setting mpi info: romio_ds_read=disable
 1:  Setting mpi info: romio_ds_write=disable
 1:  perturbation_growth_init        : PERGRO not implemented for RRTMGP, doing noth
 1:  ing.
 1:  read_char_vec: can't read variable gas_names
```

**Comment by brhillman** [comment] 2018-11-15 22:35
@amametjanov this is using the brhillman/atm/update-rrtmgp-inputdata branch on Edison? I'm retrying using your suggestion to remove the hdf5-parallel module from the env file.

**Comment by amametjanov** [comment] 2018-11-15 23:41
Yes, that path should be readable. This was with hdf5 and build commit was `c60ce99`:
```
$> cat ../bld/GIT_DESCRIBE
acme-split-2018-09-10-85-gc60ce9933
```

**Comment by brhillman** [comment] 2018-11-15 23:54
Ah, okay I see the problem, I neglected to remove an old file from the repo. It should be fixed now.

**Closed** 2019-01-21 18:33 UTC
Labels: Titan
