### ISSUE TITLE
build error in scorpio for gnu/linux

### ISSUE THREAD

**Issue by rgknox** [E3SM-Project/E3SM#3664] opened 2020-06-23 14:05 UTC
I'm getting build errors in the file: /home/rgknox/E3SM/externals/scorpio/tools/util/spio_misc_tool_utils.cxx

gnu compiler 7.3
mpi-serial
machine: eddi (linux workstation)
Tried with both PIO1/2 same error triggers, see end of log here:

```
Warning:  put_vara_internal_text  defined but not used [-Wunused-function]
f951: Warning: Nonexistent include directory  /home/rgknox/LandRuns/E3SM/fates-eca-bci-psupp-sci1.37-v1.eddi.gnu.C61f035220-Fe74106d5.2020-06-23/bld/gnu/mpi-serial/debug/nothreads/mct/mct/noesmf/c1a1l1i1o1r1g1w1i1e1/include  [-Wmissing-include-dirs]
f951: Warning: Nonexistent include directory  /home/rgknox/LandRuns/E3SM/fates-eca-bci-psupp-sci1.37-v1.eddi.gnu.C61f035220-Fe74106d5.2020-06-23/bld/gnu/mpi-serial/debug/nothreads/mct/mct/noesmf/c1a1l1i1o1r1g1w1i1e1/include  [-Wmissing-include-dirs]
/home/rgknox/E3SM/externals/scorpio/src/flib/pio_nf_utils.F90:86:0:

         allocate(cval(strlength))
 
Warning:  <anonymous>  may be used uninitialized in this function [-Wmaybe-uninitialized]
cc1plus: warning: command line option  -fbacktrace  is valid for Fortran but not for C++
cc1plus: warning: command line option  -fbacktrace  is valid for Fortran but not for C++
/home/rgknox/E3SM/externals/scorpio/tools/util/spio_misc_tool_utils.cxx: In function  bool spio_tool_utils::gsuccess(MPI_Comm, int) :
/home/rgknox/E3SM/externals/scorpio/tools/util/spio_misc_tool_utils.cxx:30:47: error:  MPI_C_BOOL  was not declared in this scope
     mpierr = MPI_Allreduce(&lsucc, &gsucc, 1, MPI_C_BOOL, MPI_LAND, comm);
                                               ^~~~~~~~~~
/home/rgknox/E3SM/externals/scorpio/tools/util/spio_misc_tool_utils.cxx:30:47: note: suggested alternative:  MPI_BXOR 
     mpierr = MPI_Allreduce(&lsucc, &gsucc, 1, MPI_C_BOOL, MPI_LAND, comm);
                                               ^~~~~~~~~~
                                               MPI_BXOR
gmake[2]: *** [tools/spio_finfo/CMakeFiles/spio_finfo.exe.dir/__/util/spio_misc_tool_utils.cxx.o] Error 1
gmake[1]: *** [tools/spio_finfo/CMakeFiles/spio_finfo.exe.dir/all] Error 2
```

I'm not too knowledgeable with c++, but after some light skimming, I did see that MPI_C_BOOL datatype is incompatible with c++.  Maybe there is a problem with a pre-processor step for me, but if not, perhaps this could be re-written to use integer communicators?

**Comment by jayeshkrishna** [comment] 2020-06-23 14:47
This is a duplicate of a Scorpio issue : https://github.com/E3SM-Project/scorpio/issues/313

**Comment by jayeshkrishna** [comment] 2020-06-23 14:48
As a workaround for mpi-serial you can use Scorpio classic (change PIO_VERSION to 1 in env_build.xml)

**Comment by rgknox** [comment] 2020-06-23 15:17
Thanks @jayeshkrishna , I will try again, but setting PIO_VERSION to 1 didn't work for me.

**Comment by rljacob** [comment] 2020-06-23 16:08
If its a build error, don't we need to somehow prevent building of Scorpio and only build scropio-classic?  There's no variable for that.

**Comment by jayeshkrishna** [comment] 2020-06-23 16:29
CIME chooses the library to build (scorpio classic vs scorpio) based on the PIO_VERSION setting in env_build.xml (PIO_VERSION = 1 vs PIO_VERSION=2). So changing PIO_VERSION=1 in env_build.xml should work for this issue.

**Comment by rgknox** [comment] 2020-06-23 16:41
I tried again was successful in getting pio to build with PIO_VERSION=1.  Not sure why my attempts to switch it before didn't work...  Thanks again

**Comment by rljacob** [comment] 2020-06-23 18:11
Ok cool.   I was thinking of PIO_TYPENAME.

**Closed** 2020-09-16 18:56 UTC
Labels: SCORPIO, bug
