### ISSUE TITLE
anvil maint-2.0 F-case wcprod test failure traced to a recent CIME update

### ISSUE THREAD

**Issue by wlin7** [E3SM-Project/E3SM#5024] opened 2022-06-15 23:23 UTC
The following anvil maint-2.0 prod tests have been failing since June 7th.

- [SMS.ne30pg2_r05_oECv3.F20TR.anvil_intel.eam-wcprod](https://my.cdash.org/test/57103719)
- [SMS_Ln5.ne30pg2_r05_oECv3.F2010.anvil_intel.eam-wcprod](https://my.cdash.org/test/57103724)

Further tests showed the problem only occurs to anvil and when running on tri-grid. The tests ran ok on chrysalis. The tests also went ok on anvil with v2 standard LR grid ne30pg2_EC30to60E2r2. 

Additional digging showed that the problem existed after PR #5005 for a CIME update. Anvil tri-grid tests were ok up to the May 27th commit of  fa8b665977a7bbb20fa0d24b503e69e96a951565.

**Comment by rljacob** [comment] 2022-06-16 03:55
It must have been caused by PR #4990 which was merged to maint-2.0 on June 7th.

**Comment by wlin7** [comment] 2022-06-16 04:30
PR #4990 also came to my mind initially given the timing. But it couldn't be #4990, which only modify several use case files for SSP compsets. Plus, June 7th test was returned before 9 AM, while #4990 was merged at 6 PM. I did also check out the commit of #5005  (af7e689913b22158e8c86705341fb04e49f85df0) for the test to draw the conclusion that it is due to #5005. Nevertheless, it is odd anvil has the problem while chrysalis not.

The error occur during ice initialization involving PIO -- back tracing as follows,
 ```
         0000000002F4E1A1  piolib_mod_mp_pio        1001  piolib_mod.F90
          0000000002A1026D  mpas_io_mp_mpas_i         306  mpas_io.f90
          0000000002B4CA5F  mpas_io_streams_m         105  mpas_io_streams.f90
          0000000002A3C873  mpas_stream_manag        3683  mpas_stream_manager.f90
          0000000002A3AF2C  mpas_stream_manag        3508  mpas_stream_manager.f90
          0000000002B36403  seaice_core_mp_se         111  mpas_seaice_core.f90
          000000000261E362  ice_comp_mct_mp_i         618  ice_comp_mct.f90
```

**Comment by jayeshkrishna** [comment] 2022-06-16 05:54
The trace above points to the PIO_openfile() call. You might want to print out the arguments in MPAS, mpas_io.f90 (the file being opened etc)

**Comment by jayeshkrishna** [comment] 2022-06-16 22:53
I just tried the first test (SMS.ne30pg2_r05_oECv3.F20TR.anvil_intel.eam-wcprod) on Anvil and it was failing when opening a file (/lcrc/group/e3sm/data/inputdata/ice/mpas-cice/oEC60to30v3/seaice.EC60to30v3.161222.nc) during ICE initialization. This looks like a memory issue to me. The same test ran successfully after changing MAX_TASKS_PER_NODE & MAX_MPITASKS_PER_NODE to 18 (from 36)

**Comment by jayeshkrishna** [comment] 2022-06-17 17:31
For SMS.ne30pg2_r05_oECv3.F20TR.anvil_intel.eam-wcprod before CIME update (v2.0.0-924-g3580f6f51e ; #3580f6f51e07f684b176a90597157b79104a4aba), env_mach_pes.xml,
```
    <entry id="NTASKS">
      <type>integer</type>
      <values>
        <value compclass="ATM">288</value>
        <value compclass="CPL">288</value>
        <value compclass="OCN">288</value>
        <value compclass="WAV">1</value>
        <value compclass="GLC">1</value>
        <value compclass="ICE">288</value>
        <value compclass="ROF">288</value>
        <value compclass="LND">288</value>
        <value compclass="ESP">1</value>
        <value compclass="IAC">1</value>
      </values>
      <desc>number of tasks for each component</desc>
    </entry>

```
After CIME update (latest master of maint-2.0, v2.0.0-930-g6275091262, #6275091262780c7a4b54ba56dcfa013ab1efa149), the env_mach_pes.xml,
```
    <entry id="NTASKS">
      <type>integer</type>
      <values>
        <value compclass="ATM">128</value>
        <value compclass="CPL">128</value>
        <value compclass="OCN">128</value>
        <value compclass="WAV">128</value>
        <value compclass="GLC">128</value>
        <value compclass="ICE">128</value>
        <value compclass="ROF">128</value>
        <value compclass="LND">128</value>
        <value compclass="ESP">1</value>
        <value compclass="IAC">1</value>
      </values>
      <desc>number of tasks for each component</desc>
    </entry>

```
The latest E3SM master also has same PE layout as maint-2.0 before the CIME update (the first case above).
@jgfouca any ideas on what changed in CIME update on maint-2.0 to give the new PE layout for this test ?

**Comment by tangq** [comment] 2022-06-17 19:01
A similar PE layout issue was reported (https://github.com/E3SM-Project/E3SM/issues/5025) for maint-2.0 F-case on the NA RRM grids.

**Comment by jayeshkrishna** [comment] 2022-06-18 20:47
Copying components/eam/cime_config/config_pes.xml from E3SM master to maint-2.0 and rerunning the test (SMS.ne30pg2_r05_oECv3.F20TR.anvil_intel.eam-wcprod) works, the test PASSes.

@wlin7 / @jgfouca : There are many changes between the config_pes.xml (EAM) on E3SM master and maint-2.0, is it safe to copy it?

**Comment by rljacob** [comment] 2022-06-20 02:39
Yes it is safe to copy it over.

**Comment by wlin7** [comment] 2022-06-20 04:01
Thanks for isolating the problem, @jayeshkrishna . Second Rob's comment above. The config_pes.xml in master is being used for anvil's e3sm_prod_next_intel tests -- the same set of tests as for maint-2.0; and the tests have been going well. Copying it to maint-2.0 should do well for all the tests, and also help with other potential PE layout issues with maint-2.0 , such as #5025.

**Comment by jayeshkrishna** [comment] 2022-06-27 19:27
Fixed by https://github.com/E3SM-Project/E3SM/pull/5037

**Closed by jayeshkrishna** 2022-06-27 19:27 UTC
Labels: bug, Atmosphere, CIME, maint-2.0
