### ISSUE TITLE
case ne30_oECv3_ICG.A_WCYCL1850S_CMIP6 with allactive-v1cmip6 mods failing

### ISSUE THREAD

**Issue by bishtgautam** [E3SM-Project/E3SM#3340] opened 2019-12-05 18:30 UTC
The main v1 fully coupled case (part of e3sm-integration) has been failing since the PR #3133 merged on Nov 27 on some macines.
 integration test:   SMS_D_Ld1.ne30_oECv3_ICG.A_WCYCL1850S_CMIP6.mach_compiler.allactive-v1cmip6

sandiatoss3-master-int:  fail since Nov28
sandiatoss3-next-int: fail since Nov 27
anvil-next-int:  fail since Nov 27  9b631d03

Runs fine:
theta-next-int:  dc19b1606 passing
bebop-next-int:   dc19b160 passed on Dec 13 (PEND since).

Notably, the production test with the same compset but without debugging has not failed on anvil.
SMS_Ld2.ne30_oECv3_ICG.A_WCYCL1850S_CMIP6.anvil_intel.allactive-v1cmip6

https://my.cdash.org/testDetails.php?test=52192958&build=1739857

**Comment by jonbob** [comment] 2019-12-05 19:24
@bishtgautam - I just checked out master and tried this test on compy with the intel compiler. I got a completely different traceback than we saw on sandiatoss3:
```   0: Image              PC                Routine            Line        Source
   0: e3sm.exe           000000000E1EB05B  Unknown               Unknown  Unknown
   0: e3sm.exe           000000000E24F106  Unknown               Unknown  Unknown
   0: e3sm.exe           0000000008400CC0  accumulmod_mp_pri         221  accumulMod.F90
   0: e3sm.exe           0000000004E18C38  clm_initializemod         642  clm_initializeMod.F90
   0: e3sm.exe           0000000004D8432D  lnd_comp_mct_mp_l         281  lnd_comp_mct.F90
   0: e3sm.exe           000000000046B2F3  component_mod_mp_         257  component_mod.F90
   0: e3sm.exe           000000000042AB7C  cime_comp_mod_mp_        1344  cime_comp_mod.F90
   0: e3sm.exe           0000000000461DB7  MAIN__                    122  cime_driver.F90
   0: e3sm.exe           0000000000418AE2  Unknown               Unknown  Unknown
   0: libc-2.17.so       00002B7B487FB3D5  __libc_start_main     Unknown  Unknown
   0: e3sm.exe           00000000004189E9  Unknown               Unknown  Unknown
```
which ended up just being a format problem. There is a character string that is longer than the format, as well as an integer value. I modified line 237 in accumulMod.F90 to look like:
```
1003 format((1x,i2),(1x,a10),(1x,a8),(1x,a8), (1x,i6),(1x,f4.0),(1x,a40))
```
and it now fails in the cospsimulator of CAM:
```
  0: forrtl: error (65): floating invalid
   0: Image              PC                Routine            Line        Source
   0: e3sm.exe           000000000E1FC1E4  Unknown               Unknown  Unknown
   0: libpthread-2.17.s  00002B68E71905D0  Unknown               Unknown  Unknown
   0: e3sm.exe           00000000023495AC  cospsimulator_int        2503  cospsimulator_intr.F90
   0: e3sm.exe           0000000001415929  radiation_mp_radi        1572  radiation.F90
   0: e3sm.exe           0000000002860350  physpkg_mp_tphysb        2765  physpkg.F90
   0: e3sm.exe           00000000028274F2  physpkg_mp_phys_r        1047  physpkg.F90
   0: e3sm.exe           000000000087B939  cam_comp_mp_cam_r         250  cam_comp.F90
   0: e3sm.exe           000000000084D17B  atm_comp_mct_mp_a         574  atm_comp_mct.F90
   0: e3sm.exe           000000000047A74A  component_mod_mp_         737  component_mod.F90
   0: e3sm.exe           0000000000441382  cime_comp_mod_mp_        2795  cime_comp_mod.F90
   0: e3sm.exe           0000000000461E53  MAIN__                    133  cime_driver.F90
   0: e3sm.exe           0000000000418AE2  Unknown               Unknown  Unknown
   0: libc-2.17.so       00002B68E76C13D5  __libc_start_main     Unknown  Unknown
   0: e3sm.exe           00000000004189E9  Unknown               Unknown  Unknown
```

**Comment by bishtgautam** [comment] 2019-12-05 19:34
@jonbob  :pray:. I guess it is now in @singhbalwinder's court.

**Comment by jonbob** [comment] 2019-12-05 19:36
Ha! Just weird that it went off the rails somewhere completely different on sandiatoss3. I'll try anvil as well, though it seems overloaded right now...

**Comment by singhbalwinder** [comment] 2019-12-05 19:39
Luckily @dqwu has a fix for this issue in #3317. @jonbob would you please try this fix to see if it helps. Thanks!

**Comment by jonbob** [comment] 2019-12-05 19:41
@singhbalwinder - that was quick! Let me give that a try... and see who it points to next 😱

**Comment by jonbob** [comment] 2019-12-05 20:00
@singhbalwinder - after merging that branch, it points into prep_rof_mod, very much like on sandiatoss3:
```
 538: forrtl: error (65): floating invalid
 538: Image              PC                Routine            Line        Source
 538: e3sm.exe           000000000E1FCCA4  Unknown               Unknown  Unknown
 538: libpthread-2.17.s  00002ACE4532B5D0  Unknown               Unknown  Unknown
 538: e3sm.exe           000000000082E61E  seq_map_mod_mp_se         869  seq_map_mod.F90
 538: e3sm.exe           000000000082C432  seq_map_mod_mp_se         788  seq_map_mod.F90
 538: e3sm.exe           0000000000819301  seq_map_mod_mp_se         311  seq_map_mod.F90
 538: e3sm.exe           00000000005D23C8  prep_rof_mod_mp_p         654  prep_rof_mod.F90
 538: e3sm.exe           000000000045B50D  cime_comp_mod_mp_        4164  cime_comp_mod.F90
 538: e3sm.exe           000000000043F86A  cime_comp_mod_mp_        2580  cime_comp_mod.F90
 538: e3sm.exe           0000000000461E53  MAIN__                    133  cime_driver.F90
 538: e3sm.exe           0000000000418AE2  Unknown               Unknown  Unknown
 538: libc-2.17.so       00002ACE4585C3D5  __libc_start_main     Unknown  Unknown
 538: e3sm.exe           00000000004189E9  Unknown               Unknown  Unknown
```

**Comment by jonbob** [comment] 2019-12-05 20:00
And pretty much the same thing on anvil:
```
 762: forrtl: error (65): floating invalid
 762: Image              PC                Routine            Line        Source
 762: e3sm.exe           000000000F8A9261  Unknown               Unknown  Unknown
 762: e3sm.exe           000000000F8A739B  Unknown               Unknown  Unknown
 762: e3sm.exe           000000000F8530E4  Unknown               Unknown  Unknown
 762: e3sm.exe           000000000F852EF6  Unknown               Unknown  Unknown
 762: e3sm.exe           000000000F7CEE07  Unknown               Unknown  Unknown
 762: e3sm.exe           000000000F7DAE9D  Unknown               Unknown  Unknown
 762: libpthread-2.17.s  00002AB0774C15D0  Unknown               Unknown  Unknown
 762: e3sm.exe           000000000D76C463  m_matattrvectmul_         267  m_MatAttrVectMul.F90
 762: e3sm.exe           000000000D773C42  m_matattrvectmul_         608  m_MatAttrVectMul.F90
 762: e3sm.exe           000000000080D3F4  seq_map_mod_mp_se         880  seq_map_mod.F90
 762: e3sm.exe           00000000007F8B4C  seq_map_mod_mp_se         319  seq_map_mod.F90
 762: e3sm.exe           00000000005BCDA4  prep_rof_mod_mp_p         696  prep_rof_mod.F90
 762: e3sm.exe           0000000000454531  cime_comp_mod_mp_        4166  cime_comp_mod.F90
 762: e3sm.exe           000000000043ACD6  cime_comp_mod_mp_        2580  cime_comp_mod.F90
 762: e3sm.exe           0000000000459688  MAIN__                    133  cime_driver.F90
 762: e3sm.exe           0000000000415A2E  Unknown               Unknown  Unknown
 762: libc-2.17.so       00002AB079C0D3D5  __libc_start_main     Unknown  Unknown
 762: e3sm.exe           0000000000415929  Unknown               Unknown  Unknown
```

**Comment by jonbob** [comment] 2019-12-05 20:03
It appears to have something to do with the "allactive-v1cmip6" changes -- SMS_D_Ld1.ne30_oECv3_ICG.A_WCYCL1850S_CMIP6.compy_intel ran fine

**Comment by singhbalwinder** [comment] 2019-12-05 20:08
Here are the files which are used for allactive-v1cmip6: https://github.com/E3SM-Project/E3SM/tree/master/cime/config/e3sm/testmods_dirs/allactive/v1cmip6

From a quick scan, it looks like it is turning on cosp and some high frequency output.

**Comment by jonbob** [comment] 2019-12-05 20:10
I agree, @singhbalwinder -- I don't see anything suspicious...

**Comment by jonbob** [comment] 2019-12-11 22:59
I'm testing a new atm2rof map for this issue and it's passing (most of the time, though compy has its own issues right now). If the next one works as well, I'll try on anvil

**Comment by jonbob** [comment] 2019-12-18 20:28
After testing on compy and anvil, here are a few results to add:
* failures are intermittent and not repeatable
* in non-debug mode, this test seems to pass consistently
* without the testmods, this test seems to pass consistently
* with cosp on but extra output dialed back, this test seems to pass consistently
* failures in debug mode point into pre_rof_mod
* failures in debug mode occur on processors shared by atm and cpl
* memory high-water reports on tests that pass don't show extreme memory usage but do
  indicate atm/cpl use the most memory
* using a bilinear map instead of conservative for atm2rof increases the chances of the test
  completing successfully (connectivity matrix size decreases from 590K to 165K entries)
All of this points to a possible memory issue, though it's not clear why the mosart-heat PR causes this test to fail. It does bring in additional cpl fields and maps for atm2rof -- @rljacob, maybe it makes sense to check that all the changes to the cpl for mosart-heat are correct?

**Comment by jonbob** [comment] 2019-12-18 20:29
I'm trying with the pgi compiler on compy, just in case a different compiler gives us different failure information...

**Comment by jonbob** [comment] 2019-12-20 20:38
The PGI run did help -- I got a core file I can use totalview on and it's pointing out some issues with the way mosart-heat was integrated into the cpl. @rljacob - I'm sure I'll need your help to figure out the right way to fix this. As far as I can tell, the problem is in prep_rof_init:
```
       if (lnd_c2_rof) then
          if (iamroot_CPLID) then
             write(logunit,*) ' '
             write(logunit,F00) 'Initializing mapper_Fl2r'
          end if
          call seq_map_init_rcfile(mapper_Fl2r, lnd(1), rof(1), &
               'seq_maps.rc','lnd2rof_fmapname:','lnd2rof_fmaptype:',samegrid_lr, &
               string='mapper_Fl2r initialization', esmf_map=esmf_map_flag)

          ! We'll map irrigation specially, so exclude this from the list of l2r fields
          ! that are mapped "normally". Note that the following assumes that all
          ! x2r_fluxes are lnd2rof (as opposed to coming from some other component).
          !
          ! (This listDiff works even if have_irrig_field is false.)
          call shr_string_listDiff( &
               list1 = seq_flds_x2r_fluxes, &
               list2 = irrig_flux_field, &
               listout = lnd2rof_normal_fluxes)
       endif
```

The assumption that all fluxes in seq_flds_x2r_fluxes are lnd2rof is no longer true, due to the addition of atm2rof fluxes. So the error is real because some aVect copy occurs later in prep_rof_calc_l2r_rx where the two aVects have different sizes.

**Comment by jonbob** [comment] 2019-12-20 20:43
@rljacob - I'm testing an uneducated fix...

**Comment by rljacob** [comment] 2019-12-21 01:31
You're right there's a problem there.  In the mapping call in prep_rof_calc_l2r_rx
```
       call seq_map_map(mapper_Fl2r, l2racc_lx(eli), l2r_rx(eri), &
            fldlist=lnd2rof_normal_fluxes, norm=.true., &
            avwts_s=fractions_lx(efi), avwtsfld_s='lfrin')
```
The fldlist has more attributes then what l2racc was initialized with.

Attention @hydrotian and @liho745 .  See above discussion.

**Comment by jonbob** [comment] 2019-12-23 16:23
@rljacob - Thanks for looking at this. I'm testing a more thought-out fix and should know soon if it works.

**Comment by jonbob** [comment] 2020-01-02 17:57
@rljacob - I have a fix and it now passes this test, at least with intel. On compy, pgi complains about some array syntax in cosp -- but passes if I replace the offending lines with do-loops. I looked at the cpl history file with ncview and the x2r fields look ok coming from both lnd and atm. But I'm not sure my solution is the right way -- it's not a part of the cpl I've done much with. I'll make a branch and ask you to look at it? And please let me know if there's a better way... Thanks

**Comment by jonbob** [comment] 2020-01-02 19:26
@rljacob - I made the branch, jonbob/cpl/fix-rof-with-atm, whenever you have time to look at it

**Comment by rljacob** [comment] 2020-01-14 20:05
I looked at it but not sure its right.  You're changing l2r_rx and a2r_rx everywhere.   Are you sure some other field isn't being dropped from those attribute vectors?

**Comment by jonbob** [comment] 2020-01-21 22:05
@rljacob - l2r_rx had been getting loaded with everything in x2r, which was OK when lnd was the only component sending anything to mosart. So I had created a new rList that only contains the l2x fluxes that actually get sent to mosart. Similarly, a2r_rx had been using seq_flds_a2x_states and seq_flds_a2x_fluxes for the fldlist -- but not all fields the atm sends to the cpl actually get sent to rof. So I made new fldlists for seq_flds_a2x_states_to_rof and seq_flds_a2x_fluxes_to_rof. And fill them in seq_flds_mod. Not as pretty a solution as there may possible be, but I don't know of another way to extract or separate which ones actually get sent to rof

**Comment by rljacob** [comment] 2020-02-24 22:45
Possible fix is in https://github.com/E3SM-Project/E3SM/pull/3460

**Comment by susburrows** [comment] 2020-04-10 23:25
> And pretty much the same thing on anvil:
> 
> ```
>  762: forrtl: error (65): floating invalid
>  762: Image              PC                Routine            Line        Source
>  762: e3sm.exe           000000000F8A9261  Unknown               Unknown  Unknown
>  762: e3sm.exe           000000000F8A739B  Unknown               Unknown  Unknown
>  762: e3sm.exe           000000000F8530E4  Unknown               Unknown  Unknown
>  762: e3sm.exe           000000000F852EF6  Unknown               Unknown  Unknown
>  762: e3sm.exe           000000000F7CEE07  Unknown               Unknown  Unknown
>  762: e3sm.exe           000000000F7DAE9D  Unknown               Unknown  Unknown
>  762: libpthread-2.17.s  00002AB0774C15D0  Unknown               Unknown  Unknown
>  762: e3sm.exe           000000000D76C463  m_matattrvectmul_         267  m_MatAttrVectMul.F90
>  762: e3sm.exe           000000000D773C42  m_matattrvectmul_         608  m_MatAttrVectMul.F90
>  762: e3sm.exe           000000000080D3F4  seq_map_mod_mp_se         880  seq_map_mod.F90
>  762: e3sm.exe           00000000007F8B4C  seq_map_mod_mp_se         319  seq_map_mod.F90
>  762: e3sm.exe           00000000005BCDA4  prep_rof_mod_mp_p         696  prep_rof_mod.F90
>  762: e3sm.exe           0000000000454531  cime_comp_mod_mp_        4166  cime_comp_mod.F90
>  762: e3sm.exe           000000000043ACD6  cime_comp_mod_mp_        2580  cime_comp_mod.F90
>  762: e3sm.exe           0000000000459688  MAIN__                    133  cime_driver.F90
>  762: e3sm.exe           0000000000415A2E  Unknown               Unknown  Unknown
>  762: libc-2.17.so       00002AB079C0D3D5  __libc_start_main     Unknown  Unknown
>  762: e3sm.exe           0000000000415929  Unknown               Unknown  Unknown
> ```

I encountered the same error / nearly identical traceback today while trying to run a F20TRC5-CMIP6 compset on cori-knl using the intel compiler, from the current hash of maint-1.0 (7175ee191388c8bda9832740077c32104e574765).  Looks like maybe the fix for this issue is also needed on the maint-1.0 branch?

**Comment by rljacob** [comment] 2020-04-10 23:29
We're pretty sure the problem was caused by Mosart-heat which isn't on maint-1.0.

**Comment by susburrows** [comment] 2020-04-10 23:35
Oops - I just realized I have accidentally built master instead of maint-1.0.  Sorry for the distraction!

**Closed** 2020-04-28 17:15 UTC
Labels: River, bug
