### ISSUE TITLE
Incompatibility between Scorpio classic and Scorpio on case_name read from restart file cpl.r

### ISSUE THREAD

**Issue by wlin7** [E3SM-Project/E3SM#3700] opened 2020-07-15 01:39 UTC
This problem emerged during a testing of relative IO performance on writing clm2.r at r0125 resolution. Note that it is reported that Scorpio (PIO_VERSION=2) appears to be slower on writing clm2.r at this resolution.

An existing case, built with Scorpio (PIO_VERSION=2), compset=ICRUCLM45,  grid=r0125_r0125_oRRS18to6v3, was used.  Restart files were from the run with Scorpio (PIO_VERSION=2). 

The case was then rebuilt, after resetting PIO_VERSION=1, followed by ./case.build --clean-all.

The restart run failed during the comparison of case_name and rest_case_came with following error msg and  back tracing

```
ERROR: 
   0:  (seq_infodata_Check) : invalid continue restart case name = 20200703.ICRUCLM45. r0125_oRRS18to6v3^@^@^@...
 
   0: e3sm.exe           00000000011B7697  seq_infodata_mod_        2624  seq_infodata_mod.F90
   0: e3sm.exe           0000000000422ACC  cime_comp_mod_mp_        1011  cime_comp_mod.F90
   0: e3sm.exe           0000000000424C4E  MAIN__                    106  cime_driver.F90


```
The actual case name is 20200703.ICRUCLM45. r0125_oRRS18to6v3.

The variables case_name read from drv_in and rest_case_name read from cpl.r need to match for a restart run. In seq_infodata_Check, the trimmed names are used in the comparison. However, the case_name read from cpl.r is padded with something other than blank space or null character  -- ^@^@^@ in print as shown above. This causes case_name and rest_case_name to not match and the restart run was aborted.

The restart run would work well if staying with Scorpio (PIO_VERSION=2).

Is this behavior expected? The problem is not really a concern because rarely one would switch PIO version during the course of a case simulation. The current case is considered a special one.

**Comment by jayeshkrishna** [comment] 2020-07-15 02:31
Could be a duplicate of https://github.com/E3SM-Project/E3SM/issues/3667

**Comment by wlin7** [comment] 2020-07-15 04:00
Does sound similar, @jayeshkrishna . In the current case, when the char variable in restart file is written and read by PIO2, it appears to be well taken care of. Could null character paddings be seen differently by PIO1 and PIO2?

**Comment by dqwu** [comment] 2020-08-19 21:42
@wlin7 @jayeshkrishna 
Is this issue only reproducible with PGI compilers?

**Comment by rljacob** [comment] 2020-08-19 22:10
Pretty sure @wlin7 was not using PGI when he saw this.

**Comment by jayeshkrishna** [comment] 2020-09-04 01:20
@wlin7, can you try out the fix for Scorpio classic in jayeshkrishna/support_c_text_vars to see if it fixes your issue (My simple tests show that the fix allows Scorpio classic to read strings written out by Scorpio)? To try out the fix,

* cd <E3SM_SOURCE_DIR>/externals/scorpio_classic
* git fetch origin
* git checkout jayeshkrishna/support_c_text_vars

and then re-run your test

**Comment by wlin7** [comment] 2020-09-13 15:02
Thanks @jayeshkrishna ,the issue is fixed by using the new branch as you instructed. Sorry for the late response. I was not tracking this thread once having PIO2 work well with a more appropriate stripe count for lfs o cori.

**Comment by rljacob** [comment] 2020-09-13 17:54
Don't close the issue unless it is fixed on master.

**Comment by jayeshkrishna** [comment] 2020-09-14 03:11
This issue will be fixed/closed when we merge the PR with the Scorpio changes to master

**Closed** 2020-09-16 18:56 UTC
Labels: SCORPIO, bug
