### ISSUE TITLE
Fails to do the branch run in E3SMv2.0 on Perlmutter due to the land restart

### ISSUE THREAD

**Issue by shipf16** [E3SM-Project/E3SM#5728] opened 2023-05-25 21:36 UTC
Hello, everyone,

I'm encountering some difficulties conducting the branch run in E3SM v2.0 using the before restart files on the Perlmutter machine.

Yesterday I downloaded the E3SM v2.0 on the Perlmutter machine using this command: git clone -b maint-2.0 --recursive [git@github.com:E3SM-Project/E3SM.git](mailto:git@github.com:E3SM-Project/E3SM.git). However, I couldn’t conduct the branch run from the restart file using E3SM v2.0 on the Perlmutter. I also add the “check_finidat_fsurdat_consistency = .false.” in the run script before building E3SM v2.0.
 
I've attached the resulting e3sm.log.error file for your review. At your convenience, could you please offer further insight into how this issue may be resolved?

Please accept my apologies for any inconvenience caused and thank you very much! I would greatly appreciate any guidance or advice you could provide to help me resolve this problem.

The below is e3sm_log for your further review:

<img width="1530" alt="e3sm log error" src="https://github.com/E3SM-Project/E3SM/assets/112215261/243cd551-d55c-42d5-b3a3-739fc359921f">

**Comment by proteanplanet** [comment] 2023-05-25 22:03
I believe this is the same issue as listed at https://github.com/E3SM-Project/E3SM/issues/5700

**Comment by erinethomas** [comment] 2023-05-25 22:04
I also need to run a v2.0 simulation on Perlmutter ASAP. Hope this issue gets resolved quickly.

**Comment by rljacob** [comment] 2023-05-25 22:11
duplicate of #5700.  Everyone interested should comment/follow that issue.

**Closed by rljacob** 2023-05-25 22:11 UTC
