### ISSUE TITLE
maint-1.0 fatal error with Scorpio 

### ISSUE THREAD

**Issue by wlin7** [E3SM-Project/E3SM#4415] opened 2021-07-17 12:46 UTC
Cases using maint-1.0 got fatal error when using Scorpio, PIO_VERSION=2 (default since May 10 after PR #4193):

`PIO: FATAL ERROR: Aborting... An error occured, Syncing file (ncid=131) failed. Invalid file id. Unable to find internal structure associated with the file id. err=-33. Aborting since the error handler was set to PIO_INTERNAL_ERROR... (/gpfs/fs1/home/ac.wlin/E3SM/integration/E3SM.maint-1.0/externals/scorpio/src/clib/pio_file.c: 233)`

This problem exists at least on compy and chrysalis.
The runs would be ok if using PIO_VERSION=1. But the problem seems not cause by PR #4193 which updated scorpio. Using the commit immediately before  #4193 also has the same behavior: Scorpio classic (PIO_VERSION=1) ok, but Scorpio (PIO_VERSION=2) not. 

There is also a seemingly unexplained behavior. The problem does not occur to short runs ( a few steps or a few days), although they also set to write history and restart files. The tests so far show the fatal run occur just before finishing the 1st month. That is probably why the issue was not captured by the nightly tests for maint-1.0.  Further examination suggests the problem likely occur when trying to write cice.h, which by default only at monthly boundary.

The problem can be reproduced using --compset FC5AV1C-L and --res ne30_oECv3, with all MPI on 4 or 16 nodes.

**Comment by jayeshkrishna** [comment] 2021-07-20 17:27
@wlin7 : Can you provide the following information for your run?
* The "git describe" output for E3SM (Run "git describe" from the main source tree) and Scorpio (Run "git describe" from inside <E3SM_SOURCE>/externals/scorpio)
* I am assuming that you are running the simulation on the latest maint-1.0 branch, if not please provide the branch you are running the simulation
* Can you add the e3sm log file in a github gist (There seems to be some mismatch between the lines reported in the error above and the version of the file in the latest version of maint-1.0 branch. I want to see if there are any errors prior to the Scorpio error etc)?

I am also going to try a month long run of the above case with 16 MPI processes and see if I can reproduce the issue.

**Comment by jayeshkrishna** [comment] 2021-07-20 17:30
This issue could be related to https://github.com/E3SM-Project/E3SM/issues/3605

**Comment by jayeshkrishna** [comment] 2021-07-20 17:36
A quick look at the ice_history_write.F90 shows potential bugs in the subroutines there (again freeing decomp associated with a file that is already closed). This could be the source of the issue that you see in your runs.

(Note: Scorpio has more error checks and hence detects these error cases that were ignored by Scorpio classic)

**Comment by jayeshkrishna** [comment] 2021-07-20 17:41
This change made in E3SM master - https://github.com/E3SM-Project/E3SM/pull/3607 - is missing in maint-1.0

**Comment by wlin7** [comment] 2021-07-20 18:31
Hi @jayeshkrishna , Looks like you already isolated the cause of the problem. Thanks for the quick works.
For reference, these are the returns from git describe 

- maint-1.0 E3SM: v1.0.0-282-ga560789
- external/scorpio: scorpio-v1.2.1

**Comment by jayeshkrishna** [comment] 2021-07-20 20:16
Thanks, I am testing out the fix in PR #4417 (draft for now) right now with a month long run. Once I have finished the testing you can try it out and see if it fixes the issue.

**Comment by wlin7** [comment] 2021-07-20 20:45
Sounds good. Thanks.

**Comment by jayeshkrishna** [comment] 2021-07-30 16:50
Fixed in https://github.com/E3SM-Project/E3SM/pull/4417

**Closed by jayeshkrishna** 2021-07-30 16:50 UTC
Labels: SCORPIO, bug, maint-1.0
