### ISSUE TITLE
Some e3sm_developer tests failed during SETUP (missing valid mapping file)

### ISSUE THREAD

**Issue by dqwu** [E3SM-Project/E3SM#3211] opened 2019-09-27 14:43 UTC
See https://my.cdash.org/viewTest.php?onlyfailed&buildid=1707407

For tests failed with 0s in Time column, they all have the following error:
`ERROR: Need to provide valid mapping file between atm and rof in xml variable atm2rof_fmapname`

Besides melvin, this is also reproducible on anlworkstation.

Is this caused by recent CIME update?

**Comment by jgfouca** [comment] 2019-09-27 17:16
@dqwu , I don't think so. I tested the CIME update on melvin before I issued the PR. I will investigate.

**Comment by jgfouca** [comment] 2019-09-27 17:20
@bishtgautam , this PR

```
 Merge branch 'hongyili/mosart/mosart-heat2' into next (PR #3133)
```

Appears to be the cause of this error.

**Comment by bishtgautam** [comment] 2019-09-27 19:46
I have reverted PR #3133 from next as it cause multiple runtime failures. I will leave this issue open because it needs to be fixed before PR #3133 is re-merged to next.

**Comment by jgfouca** [comment] 2019-09-27 19:54
Since this PR is not on master, and is going through routine integration debugging, we can close this issue.

**Closed by jgfouca** 2019-09-27 19:54 UTC

**Comment by rljacob** [comment] 2019-10-01 17:34
fI a test suite is failing on next, its probably related to an in-process PR and you should either wait for it to be fixed or find the responsible PR and make a comment on it.

Issues should only be opened for problems on the master or maint branches.
