### ISSUE TITLE
Branch run failed likely due to the clm->elm name change

### ISSUE THREAD

**Issue by tangq** [E3SM-Project/E3SM#4208] opened 2021-04-07 22:23 UTC
A branch run test failed with today's master on chrysalis because it still tried to locate the land restart file with the old naming convention of `*.clm2.r.*.nc`.

The branch run capability is important for the v2 production runs as that's how we'll run the historical simulations based on the PI control. @golaz and @rljacob , I believe we need to fix this for v2.

The test is located at /lcrc/group/e3sm/ac.qtang/E3SM_simulations/20210407.tst_branch.ne30pg2_EC30to60E2r2/run

It seems to me that this is because the branch run automatically sets "nrevsn" in lnd_in with the old naming convention.

**Comment by rljacob** [comment] 2021-04-07 22:34
I think #4128 fixes this ?

**Comment by rljacob** [comment] 2021-04-07 22:34
Duplicate of #3905

**Closed by rljacob** 2021-04-07 22:34 UTC

**Comment by jonbob** [comment] 2021-04-07 22:36
@rljacob - yes, that PR should fix it

**Comment by tangq** [comment] 2021-04-07 22:38
@jonbob and @rljacob , good to know it's been reported and there is a PR waiting to be merged to fix it.

**Comment by tangq** [comment] 2021-04-07 22:44
@jonbob or @rljacob , can either of you merge #4128 today, so I can start my branch run with the master code? Thanks.

**Comment by rljacob** [comment] 2021-04-07 22:55
Done.

**Comment by tangq** [comment] 2021-04-07 22:56
Thank you, @rljacob !
