### ISSUE TITLE
SourceMods for code changes stops working

### ISSUE THREAD

**Issue by wlin7** [E3SM-Project/E3SM#5924] opened 2023-09-12 19:55 UTC
It is tested specifically for EAM, using SMS_D_Ln5.ne4_oQU240.F2010.chrysalis_intel.eam-cosplite_nhtfrq5. Any tests involving active atm should see the same. Code changes placed under a case's SourceMods/src.eam are not used to build the model. The problem exists with the current master.

Are there changes in the build system recently that acts to disable SourceMods mechanism?

**Comment by rljacob** [comment] 2023-09-12 20:11
Are you sure SourceMods was working?   The eam-cosplite_nhtfrq5 testmod doesn't have any source modifications.  It has an alternate elm namelist and an xmlchange command.   If _those_ aren't working, that's a problem.

**Comment by wlin7** [comment] 2023-09-13 03:25
The problem is independent of eam-cosplite_nhtfrq5 test. It was picked as an F case example. gnu tests for next were failing during runtime today. I used this test for debugging and started with placing the fixed file under src.eam. It was from there I found the modified file under SourceMods/src.eam was not used for rebuild -- The fix was then verified without using SourceMods.

Before reporting this issue, it was confirmed master also has the issue. The last time I used SourceMods extensively was for debugging threading/pe-layout NBFB issue with the branch for #5860. That branch was rebased with master of Aug. 7th (after the merge #5781).

**Comment by rljacob** [comment] 2023-09-13 03:28
Do you remember when that branch originally started?   So we know how far back to start.

**Comment by wlin7** [comment] 2023-09-13 03:36
The branch started around July 19th (based on an email from developer @jinboxie ). The branch was based off the previous `big v3atm PR branch` #5781 in order for testing with v3alpha02 config. It was then rebased with master after #5781 was merged.

Probably too tedious to track down the history of the #5860 branch. I feel master after #5781 (August 7th) should still work. I am going to test it to make sure.

**Comment by jinboxie** [comment] 2023-09-13 03:46
Yes. It was originally first put on here #5796 on July 5th for v3alpha01 tesing (same codebase as v3alpha02). And then rebased to master under Wuyin's suggestion and sent to #5860 branch.

**Comment by wlin7** [comment] 2023-09-13 03:52
@rljacob , it is confirmed master branch immediately after the merge commit for #5871, 915e929b5118243bc2f15b90c4ca911352985524, SourceMods can still work as intended.

Simple step to test: create a test like `SMS_D_Ln5.ne4_oQU240.F2010.pm-cpu_intel.eam-cosplite_nhtfrq5`,  copy a file say `eam/src/physics/cam/physpkg.F90` to SourceMods/src.eam. May do a small edit of the file - I did it by adding a few characters to an arbitrary `write(iulog,*)` statement. This step is optional. Then run ./case.build and check if it is recorded in `e3sm.bldlog `that the file under src.eam is compiled to build the executable.

**Comment by rljacob** [comment] 2023-09-13 04:22
The likely candidate for breaking this is the CIME update on 6aa22b163 included in PR #5812 on August 21.

**Comment by jgfouca** [comment] 2023-09-13 17:12
@wlin7 , @rljacob , I don't think #5812 should have had any effect on the build system, but I can look to confirm.

@wlin7 , can you give me an exact sequenct of shell commands that demonstrates the error?

**Comment by wlin7** [comment] 2023-09-15 02:18
@jgfouca , below are the steps I did

```
1. ./create_test SMS_D_Ln5.ne4_oQU240.F2010.pm-cpu_intel.eam-cosplite_nhtfrq5 
2. cd FULLPATH_TO_TESTDIR   # after model build completed
3. echo A=0 > SourceMods/src.eam/physpkg.F90   # if work, would break the build. Default bld uses eam/src/physics/cam/physpkg.F90
4. ./case.build # to rebuild. 
5. if 4 failed, it would be working. May also check in latest e3sm.bldlog if any attempt to build physpkg.F90

```
I just tested with current master. SourceMods still does not work.

**Comment by jgfouca** [comment] 2023-09-15 18:34
@wlin7 , I am not able to reproduce this problem.

I tried two things. First, I tried creating the case with `--no-build` and then making the source mod and trying to build. This way, the source mod is in place before any build is attempted. The build failed with the expected error:

```
% ./create_test SMS_D_Ln5.ne4_oQU240.F2010.mappy_gnu.eam-cosplite_nhtfrq5 --no-build
% cd $case
% echo A=0 > SourceMods/src.eam/physpkg.F90
% ./case.build
* FAILS *
```

Second, I tried creating the case with `--no-run` and  then making the source mod and trying to re-build. This means the source mod is only present on the rebuild. This also led to the expected build error:

```
% ./create_test SMS_D_Ln5.ne4_oQU240.F2010.mappy_gnu.eam-cosplite_nhtfrq5 --no-run
...
PASS SMS_D_Ln5.ne4_oQU240.F2010.mappy_gnu.eam-cosplite_nhtfrq5 MODEL_BUILD
% cd $case
% echo A=0 > SourceMods/src.eam/physpkg.F90
% ./case.build 
* FAILS *
```

I checked the build logs for both failed builds and they both had the expected error in physpkg.F90. I can tried pm-cpu next but I don't see why that would change anything. I am stumped at to why this would not work for you.

I used this commit:
```
% git log -1
commit 84e50561a854e1888b0eaa52fc3a44287f3a5924
Merge: a021604 8f412c6
Author: Wuyin Lin <wlin@bnl.gov>
Date:   Thu Sep 14 05:22:06 2023 -0700
```

Submodules are up-to-date.

**Comment by jgfouca** [comment] 2023-09-15 19:08
@wlin7 , interesting. I am able to reproduce the error on perlmutter.

**Comment by jgfouca** [comment] 2023-09-15 20:21
@wlin7 , for reasons I don't understand, probably due to cmake version differences, mappy reconfigures (re-runs cmake) when re-running case.build and perlmutter does not. I think I know of a good fix for this.

**Comment by wlin7** [comment] 2023-09-15 20:52
@jgfouca , thanks for digging it deeper on this issue and having the fix. I would have no clue if I saw your message regarding mappy tests in time. It is interesting mappy can still work (in the old way). I previously tested on both pm-cpu and chrysalis and neither worked. The new fix apparently  has SourceMods work more reliably.

**Closed** 2023-09-19 15:16 UTC
