### ISSUE TITLE
SCORPIO slow swapm times

### ISSUE THREAD

**Issue by mt5555** [E3SM-Project/E3SM#3650] opened 2020-06-17 20:19 UTC
A NE1024 case, on 1024 nodes with high frequency I/O was obtaining terrible I/O performance, pio_swapm times of 25min to write about 8GB of data.

Here's a smaller case that runs on Cori in the debug que.  It's much better, but still has poor I/O performance due mostly to pio_swapm times (about 246s).  

create_newcase -res ne256pg2_r0125_oRRS18to6v3 -compset FC5AV1C-L  -case io256pg2

./xmlchange ATM_NCPL=360
./xmlchange CAM_TARGET=theta-l
./xmlchange NTASKS=16384
./xmlchange NTHRDS=4
./xmlchange EPS_AGRID=1.0e-9    
./xmlchange STOP_OPTION=nsteps
./xmlchange STOP_N=2
./xmlchange REST_OPTION=never
./xmlchange JOB_WALLCLOCK_TIME=00:30:00
./xmlchange JOB_QUEUE=debug

./xmlchange NTASKS=16384
./xmlchange NTHRDS=4
./xmlchange NTASKS_LND=4096
./xmlchange ROOTPE_LND=0
./xmlchange NTASKS_ICE=4096
./xmlchange ROOTPE_ICE=4096
./xmlchange NTASKS_CPL=8192
./xmlchange ROOTPE_CPL=8192

And this add to "user_nl_cam":    some high frequency I/O and reduced timestep so the run doesn't crash:

se_tstep = 20
mfilt          = 1,8,1
nhtfrq         = 0,1,1
fincl2 = 'U250:I','V250:I','OMEGA500:I'
fincl3 = 'OMEGA:I''VOR:I','DIV:I'
ncdata = '/global/cscratch1/sd/taylorm/ape_data/cami_mam3_0000-01-ne256np4-L72.nc'

**Comment by ndkeen** [comment] 2020-06-17 20:55
I have been looking closer at the init timers and I recently added many more to a local scream repo. Initially, I was looking at ne1024 init times. However, I noticed that for ne256, which I would expect to be much faster, is running init much slower as I increase the number of MPI's.
Using ne256 and 1024 nodes, the init times are:
8 MPI's per node: 733 sec
16 MPI's per node: 1657 sec
32 MPI's per node: 4818 sec  (!!!)

Here is a case where I ran with 32 MPI's per node. This is the location of the timer checkpoint that captures only Init cost (ie before time stepping). It include many of my own timers, but they aren't necessary to see that the init in LND is clearly the major problem.

```
/global/cscratch1/sd/ndk/e3sm_scratch/cori-knl/s16-jun11/f.ne256pg2tri.s16-jun11.n1024t32x411111.wr.24s.N144.pio2.st064S2m.SST/run/timing.31795147.200615-173356/checkpoints/model_timing_20160801_00000.00000
```

**Comment by worleyph** [comment] 2020-06-17 21:39
>  but still has poor I/O performance due mostly to pio_swapm times (about 246s).

Hard to tell from these data. pio_swapm also has a "barrier-like" behavior in that it can capture load imbalances. Average total time is 5 seconds for the  io256pg2 case, so one or a few processes are holding things up (in a:PIO:box_rearrange_create).

**Comment by mt5555** [comment] 2020-06-17 23:14
initializaiton is clearly a problem - but this issue I think is not related.  Originally I noticed on 1024 nodes, writing a 2.5GB file each day, the time between files was 12min, but only 6min/day without I/O.  So it has to be the I/O, and taking 6min to write 2.5GB is extremely slow.

Going down to 512 nodes to fit in the debug que made the performance much better, but the cost of I/O is still way to large.  With this debug configuration, 246s to write 8GB of data.  

In both cases, timing data wants to blame pio_swapm, but I agree, that could be because it was to wait on other MPI tasks.

**Comment by worleyph** [comment] 2020-06-18 02:06
@mt5555 , died for me during nstep 2 with

     5197:  WARNING:CAAR: dp3d too small. dt_remap may be too large
     ...
     5197:  k,dp3d(k), dp0:            2 -0.502423282088725        7.03568251863183
     ...
     5197:  WARNING:CAAR: theta<   10.0000000000000       applying limiter
     5197:  k,vtheta(k):            1  -1779.52472132192
     ...
      5197: Image              PC                Routine            Line        Source
      5197: e3sm.exe           00000000048FB686  Unknown               Unknown  Unknown
      5197: e3sm.exe           0000000002F3BF5C  shr_abort_mod_mp_         114  shr_abort_mod.F90
      5197: e3sm.exe           0000000001D832C9  vertremap_mod_mp_         103  vertremap_mod.F90
      5197: e3sm.exe           0000000001D15CDE  prim_driver_base_        1340  prim_driver_base.F90
      5197: e3sm.exe           0000000001D14D00  prim_driver_base_        1126  prim_driver_base.F90
      5197: e3sm.exe           000000000215CDF8  dyn_comp_mp_dyn_r         376  dyn_comp.F90

with similar abort messages for other processes (but not all).

**Comment by worleyph** [comment] 2020-06-18 02:52
@mt5555 , our atm_in and drv_in files are the same, except for the model_version in drv_in. I am using the latest master. Your tag is a little older?

     <   model_version = "71dc33452"
     ---
     >   model_version = "8edb7cda78"

**Comment by mt5555** [comment] 2020-06-18 03:10
I was getting those same errors with the default timstep (40s).  I lowered it to 20s to get it to work.  Could you try editing the user_nl_cam to se_tstep=10?

**Comment by worleyph** [comment] 2020-06-18 03:12
Will do.

**Comment by mt5555** [comment] 2020-06-18 03:15
i updated to latest master - it does pull in a tweaked initial condition PR, which hopefully explains the different.  I'm going to try again as well.

**Comment by sarats** [comment] 2020-06-18 03:52
@mt5555 I pulled a hopefully related (?) experiment in PACE.
https://pace.ornl.gov/exp-details/28797

Looking at summary statistics, wallmax and wallmin, there is a wide variation which probably reflects load imbalance that @worleyph is referring to?

https://pace.ornl.gov/summary/28797/stats#summary
pio_swapm
wallmin: 2 sec (rank: 8928)
wallmax: 427 sec  (rank: 4096)

Anyway, just trying to see if any data there offers pointers.

**Comment by worleyph** [comment] 2020-06-18 12:43
@mt5555 , my second attempt "hung" early on in initialization (ran out of time, and I gave it 40 minutes). Probably just NERSC I/O issues, but am resubmitting this morning, with same se_tstep=10 .

**Comment by worleyph** [comment] 2020-06-18 13:37
Did not get through initialization (again) after 30 minutes this time (back in the debug queue). Will try again, setting an hour and watching it to make sure it is not just hung some place.

**Comment by worleyph** [comment] 2020-06-18 15:56
even 1.5 hours was not long enough to get through initialization today (still making progress, just really slow). I'll try again with se_tstep=20, just to make sure that this is not the source of the slowness (no reason for it to be, but ...)

**Comment by worleyph** [comment] 2020-06-18 17:14
So, initialization for this case yesterday took 15 minutes. Today it is taking over 90 minutes (and I am not sure how long would be required to complete initialization, much less any main loop steps and the high frequency I/O whose performance Mark was interested in looking at). So, this is not worth spending any more time or compute resources on today. @ndkeen , is this something you can ask about? Anyone else seeing I/O issues (as that has to be what this is)?

**Comment by mt5555** [comment] 2020-06-18 17:27
My first run (after updating) also didn't complete. I thought it hung and I resubmitted, but now I think some recent PR might have broken our initialization code?

**Comment by worleyph** [comment] 2020-06-18 18:14
Again, my run yesterday took ony 15 minutes. The identical job today took over 90 minutes (then timed out). It was still progressing, but very slowly. I think that it is NERSC file system I/O issues.

**Comment by dqwu** [comment] 2020-06-19 16:07
@mt5555
It seems that sometimes NERSC Community File System (CFS) might have I/O issues, causing reading E3SM input files very slow. With default input data under /global/cfs/cdirs/e3sm/inputdata, my first case run could not complete with 30-min wall time.

After I changed the input data directory to my scratch directory under /global/cscratch1 and checked out the required input files, my second case run could complete in about 10 mins.

**Comment by dqwu** [comment] 2020-06-19 16:12
@mt5555 
For your posted test case, PIOc_InitDecomp is called 40 times, and a few timer in my run are as below:
```
"a:PIO:PIOc_initdecomp"                   -      16384    16384 3.768320e+05   1.035941e+05     6.328 ( 16145      0)     6.293 (     0      0)
"a:PIO:box_rearrange_create"              -      16384    16384 3.768320e+05   1.026936e+05     6.271 (  8200      0)     6.266 ( 16332      0)
```
E3SM version is based on hash ec1a137 on May 22:
Merge branch 'jayeshkrishna/switch_to_scorpio2' (PR 3515)

**Comment by worleyph** [comment] 2020-06-19 17:25
I tried modifying the supplied PE layout to decrease initialization time (still reading from CFS), and got a few OOM failures. My most recent experiment used twice as many nodes (8 processes per node, 1024 nodes total), and this failed with 

     1511:  inconsistency between land mask and sea ice mask
     1511:  n=          182  fracl=   0.000000000000000E+000  fraci=
     1511:   0.972565098867034
     1511:  ERROR: (seq_domain_check)   inconsistency between land mask and sea ice mask

**Comment by worleyph** [comment] 2020-06-19 17:30
But the 1024 node job got through the initialization much faster than the 512 node job (until it died) :-).

**Comment by ndkeen** [comment] 2020-06-19 18:16
In the past, I've also experimented with using scratch instead of GPFS filesystem at NERSC (project directory at the time, but CFS should be same). And while the performance difference in reading between the two was difficult to ascertain, I had thought it might be a way of minimizing serious slowdowns. My conclusion was that it didn't seem to matter as at any given time there could be something happening on either filesystem. But it's good to have this as option for experimentation.

Pat: The `inconsistency between land mask and sea ice mask` error you see is something I've also been seeing with SCREAM runs for some time. For me, it happens every now and then and is a nuisance. It's not yet clear to me if it's a real problem in that sometimes a file is read "incorrectly" (where the data is not what we want and this catches it), or if there is some sort of race condition (hypothesis) such that this test fails sometimes, but not most.

**Comment by worleyph** [comment] 2020-06-20 00:54
The original (512 node job) specified by Mark, with the change to se_tstep=10, is now working fine for me. Have run twice, with the jobs taking:

(expt. 1)

    Init Time   :     643.416 seconds
    Run Time    :     487.642 seconds    87775.560 seconds/day

(expt. 2)

    Init Time   :     599.010 seconds
    Run Time    :     285.673 seconds    51421.140 seconds/day

so over 6 times faster than what I was seeing yesterday. Sure wish that we could tell what was happening to make it so much slower.

There are still non-negligible times in pio_swapm. I added some extra timers to scorpio in the first experiment, and then added barriers around the calls of interest, and the time is really being spent in pio_swapm for a call in compute_counts (called as part of box_rearrange_create):

           "a:PIO:pio_swapm_1"  -      23    -      79.127998    10.360832     0.952548         0.000070

and some cost in a call to swapm in rearrange_comp2io

           "a:PIO:pio_swapm_3"  -      28    -      21.521311     7.266668     0.002517         0.000086

These were both for the second experiment, with barriers around both of these pio_swapm calls.
Not all processes show this cost in pio_swapm, but the barrier that I added following these catches the rest. The barrier preceding these calls shows very little cost, so the cost really is in pio_swapm. 

The total pio_swapm time in these two experiments were

     "a:PIO:pio_swapm"   -      16384    16384 1.589248e+06   1.240770e+05   362.125 (  4480      0)     2.097 (  8008      0)
     "a:PIO:pio_swapm" -      16384    16384 1.589248e+06   5.500048e+04   109.718 (  1856      0)     1.965 (  5408      0)

respectively, so the second experiment, with the additional barriers, has 1/3 the pio_swapm cost, but this may or may not have anything to do with barriers. Perhaps there is that much variability in the MPI communication times? I'll look at these pio_swapm calls in more detail when I get the chance, and as long as these job continue to run quickly.

**Comment by worleyph** [comment] 2020-06-20 11:23
@jayeshkrishna and @dqwu , I've not seen performance as low as what you report in your run. However, I did look at the performance in a:PIO:pio_swapm in my runs, and noticed that of the 4 different locations for the pio_swapm calls, 3 of them used MPI_Alltoallw (hs = .false., isend = .true., max_pend_req = 0):

     2 calls in compute_counts
     1 call in rearrange_comp2io

and only one used a point-to-point communication protocol (hs = .true., isend = .false., max_pend_req = 64, and this later is what is specified in env_run.xml):

     1 call in box_rearrange_create

While the performance variability is too great to be sure about this, I did force pio_swapm to always use a point-to-point protocol (hardwired max_pend_req in the call to pio_swapm to 64), and this appeared to improve performance:

(as is)

     "a:PIO:pio_swapm"  -      16384    16384 1.589248e+06   4.790460e+04    84.186 (  2688      0)     1.948 (  7621      0)

(with point-to-point forced inside of the pio_swapm call)

     "a:PIO:pio_swapm"  -      16384    16384 1.589248e+06   1.896942e+05    13.452 (     0      0)     9.643 (     3      0)

Note that I did not force it to use handshaking, so this was without handshaking for the three calls that originally  had max_pend_req = 0. These runs were with the additional barriers surrounding the two "high cost" calls to pio_swapm, so these are true pio_swapm costs.

So, ..., why is the env_run.xml communication protocol being ignored (most of the time, but not all)?

**Comment by worleyph** [comment] 2020-06-20 11:41
I just noticed that the MPI_Alltoallw protocols are all associated with rearr_opts.comp2io, while the one point-to-point protocols is associated with rearr_opts.comp2io.

And I misinterpreted the output of the boolean values. comp2io pio_swapm calls had (hs = .true., isend = .false., max_pend_req = 0) and io2comp pio_swapm calls had 
(hs = .false, isend = .true., max_pend_req = 64), which matches env_run.xml specifications. What is missing is that 

      <entry id="PIO_REARR_COMM_MAX_PEND_REQ_COMP2IO" value="0">

is supposed to mean

     <desc>pio rearranger communication max pending requests (comp2io) : 0 implies that CIME internally calculates the value ( = max(64, 2 * PIO_NUMTASKS) ), -1 implies no bound on max pending requests </desc>

while it appears that max_pend_req is left at 0, which means to use MPI_Alltoallw .

**Comment by worleyph** [comment] 2020-06-20 11:44
And this means that when I hardwired the max_pend_req to 64, that the comp2io versions of the pio_swapm call were using handshaking.

**Comment by worleyph** [comment] 2020-06-20 20:35
I started from scratch, updating to latest master, built and ran case that Mark describes in this issue (modified to use se_tstep=10). I ran this twice, in sequence, in the debug queue, the first time with the unmodified PIO settings in env_run.xml anbd the second with

    <entry id="PIO_REARR_COMM_MAX_PEND_REQ_COMP2IO" value="64">

The e3sm.log output confirmed the difference:

    0:    max pend req (comp2io)  =           0

vs.

    0:    max pend req (comp2io)  =          64

The performance for the two was as follows:

    Init Time   :     623.199 seconds
    Run Time    :     407.493 seconds    73348.740 seconds/day

vs.

    Init Time   :     526.868 seconds
    Run Time    :     145.976 seconds    26275.680 seconds/day


and

     "a:PIO:pio_swapm"   -      16384    16384 1.589248e+06   1.130933e+05   344.048 (  3008      0)     2.002 (  1030      0)

vs.

     "a:PIO:pio_swapm"  -      16384    16384 1.589248e+06   2.013911e+05    13.918 ( 16383      0)    10.312 (     3      0)

Unfortunately, these were not on the same nodes, but the performance difference is significant enough that I believe that using MPI_Alltoallw is part of the performance issue. I'll make an issue that PIO_REARR_COMM_MAX_PEND_REQ_COMP2IO is not being interpreted correctly.

**Comment by rljacob** [comment] 2020-06-22 03:16
Pat, the first sentence in this comment is not clear:  https://github.com/E3SM-Project/E3SM/issues/3650#issuecomment-646984099

**Comment by worleyph** [comment] 2020-06-22 03:31
If the sentence is 

     I just noticed that the MPI_Alltoallw protocols are all associated 
     with rearr_opts.comp2io, while the one point-to-point protocols
     is associated with rearr_opts.comp2io.

Sorry - meant 

    ... while the one point-to-point protocol is associated with rearr_opts.io2comp.

The issue is that I added additional timers to scorpio, and noticed that most of the calls to pio_swapm were using the MPI_Alltoallw "communication protocol" internally. It was after further instrumentation (and some print statements) were added that I reallized that the MPI_Alltoallw calls were only happening in the comp2io communication pattern. The io2comp communication pattern was using a point-to-point communication protocol. The communication protocol for these are specified separately in env_run.xml.

I had printed out the logical variables as integer (this is in C code), and the two values were 255 and 0. I misremembered which corresponded to .true. and which to .false. Once I figured that out, I realized that options specified in env_run.xml were faithfully passed into scorpio for both comp2io and io2comp, EXCEPT that a value of zero for PIO_REARR_COMM_MAX_PEND_REQ_COMP2IO was passed through to pio_swapm without being "translated" to max(64, 2 * PIO_NUMTASKS) .

rearr_opts.comp2io and rearr_opts.io2comp are the internal scorpio data structures containing the communication protocols for comp2io and io2comp respectively.

**Comment by jayeshkrishna** [comment] 2020-06-22 14:32
@worleyph : Thanks for digging into this issue. It looks like ESMCI/cime@508657b26c043e5370ddba4cde9af1002c867f87 might have broken the expected behavior (Setting PIO_REARR_COMM_MAX_PEND_REQ_COMP2IO = 0 in env_run.xml does not result in CIME setting max pending requests to max(64, 2 * PIO_NUMTASKS) )

**Comment by worleyph** [comment] 2020-06-22 14:46
In any case, not sure that MPI_Alltoallw should ever be called if 

     <entry id="PIO_REARR_COMM_TYPE" value="p2p">

There are also the lines near the top of pio_rearrange.c

    /* Disable handshake /isend and set max_pend_req = 0 to turn of throttling */
    const rearr_comm_fc_opt_t def_coll_comm_fc_opts = { false, false, 0 };

As implemented. setting max_pend_req to 0 does not have anything to do with throttling (throttling is invoked by setting max_pend_req to something small, and setting it to zero calls MPI_Alltoallw). 

The comment in pio_swapm (pio_spmd.c) is equally confused:

    /* If fc->max_pend_req == 0 no throttling is requested and the default                                                                       
     * mpi_alltoallw function is used. */

To disable throttling, would want max_pend_req to be "large" or the special value '-1', as reflected in the pio_swapm logic:

      if (fc->max_pend_req == PIO_REARR_COMM_UNLIMITED_PEND_REQ)

where

     #define PIO_REARR_COMM_UNLIMITED_PEND_REQ -1

**Comment by dqwu** [comment] 2020-06-22 14:54
> @worleyph : Thanks for digging into this issue. It looks like [ESMCI/cime@508657b](https://github.com/ESMCI/cime/commit/508657b26c043e5370ddba4cde9af1002c867f87) might have broken the expected behavior (Setting PIO_REARR_COMM_MAX_PEND_REQ_COMP2IO = 0 in env_run.xml does not result in CIME setting max pending requests to max(64, 2 * PIO_NUMTASKS) )

That CIME change was merged to E3SM master branch in PR 3603 (May 29).
Likely that is why I could not reproduce the issue with old E3SM based on PR 3515 (May 22).

**Comment by jayeshkrishna** [comment] 2020-06-22 15:18
The special values for max_pend_reqs (0 implies choosing MPI_Alltoallw)  is still used in, and was inherited from, NCAR PIO. And in the PR above Jim@NCAR wanted to force using MPI_Alltoallw for mpi-serial cases.
And I agree that in none of the E3SM cases (ignoring mpi-serial) we should be using MPI_Alltoallw.
I will fix this issue in CIME soon.

**Comment by worleyph** [comment] 2020-06-22 15:32
The special values for max_pend_reqs (0 implies choosing MPI_Alltoallw)
      is still used in, and was inherited from, NCAR PIO

Not from PIO1 :-).

     !! comm_maxreq:                                                                                                                                                                                                          
     !!  =-1,0: do not limit number of outstanding send/receive requests                                                                                                                                                      
     !!     >0: do not allow more than min(comm_maxreq, steps) outstanding                                                                                                                                                    
     !!         nonblocking send requests or nonblocking receive requests                                                                                                                                                     


My comment was about the misleading comments about throttling in the code. 

With regards to mpi-serial, it is still jarring that the env_run.xml specification is being ignored in this case. Perhaps it should be documented as such (that these settings are ignored when mpi-serial is being used?). I don't really case, so please ignore this suggestion, but it did lead to a hard to diagnose error (when applied to non-mpi-serial). Something more explicit in the code perhaps could have prevented this error from occurring.

**Comment by jayeshkrishna** [comment] 2020-06-22 15:39
I agree that the setting is not intuitive (the setting was introduced in PIO2). I will create an issue in Scorpio to refactor the code to make the intent clear.

I will also add more comments in the XML file about the mpi-serial behavior.

**Comment by dqwu** [comment] 2020-06-22 15:41
> 0 implies choosing MPI_Alltoallw

One possible reason why "0 implies choosing MPI_Alltoallw" is still kept: it can be used for debugging and make sure other variations of original MPI_Alltoallw (custom implementations) can yield the correct swap results (the run time with original version can also be used to test whether other variations can improve the performance).

**Comment by jayeshkrishna** [comment] 2020-06-22 15:41
Yeah, but the setting is not intuitive (what does setting maxmum number of pending requests to 0 mean? )

**Comment by dqwu** [comment] 2020-06-22 15:43
> Yeah, but the setting is not intuitive (what does setting maxmum number of pending requests to 0 mean? )

I agree. For me, I also feel confused with related code and comments for a long time.

**Comment by worleyph** [comment] 2020-06-22 15:56
MPI_Alltoallw is a perfectly valid option, and having it appear in pio_swapm makes sense, and using max_pend_req to select this internally is convenient, but this is all internal specification. The external specification is different, and there needs to be some care in translating between the two since the same names are used. For safetys sake, perhaps a new parameter should be added to pio_swapm to select MPI_Alltoallw ('use_collective'?) that then ignores the other options?

Note that having MPI_Alltoallw be so much slower than a point-to-point algorithm has been a annoyance for many many years now (on many systems). Part of this is due to the fairly sparse communication pattern, but the problem has been "solved" on Cori-KNL for MPI_Alltoall (and perhaps for MPI_alltoallv), where there is an optimized transport layer for this collective. MPI_Alltoallw apparently is not used often enough to have been considered important enough to see a likewise optimized implementation. As you can see, the point-to-point algorithm actually works pretty well, so we can live with the lack of an efficient implementation of MPI_Alltoallw .

**Comment by worleyph** [comment] 2020-06-22 16:10
what does setting maximum number of pending requests to 0 mean?

This actually does have a real meaning - if not using nonblocking MPI commands, then there are no pending requests. In

     components/cam/src/utils/spmd_utils.F90

the routine altalltoallv calls either mpi_alltoallv, a co-array fortran algorithm, an MPI-2 one-sided algorithms, swapm (ancestor of pio_swapm), or an mpi_sendrecv based algorithm. This mpi_sendrecv-based algorithm represents an algorithm for which the number of pending requests is zero. There is also an example of this in pio_spmd.c for data copies within a processe, ifdef'ed with the token ONEWAY (not sure why this is referred to as ONEWAY though).

**Comment by jayeshkrishna** [comment] 2020-06-22 17:26
Like @worleyph mentioned in the performance call, a quick workaround would be to explicitly set PIO_REARR_COMM_MAX_PEND_REQ_COMP2IO to say 64 (By default in env_run.xml is set to 0 and due to the recent change introduced in CIME, ESMCI/cime@508657b, CIME no longer calculates and resets the value as intended. And due to this change data rearrangement in Scorpio ends up using MPI_Alltoallw instead of point to point messages)

**Comment by mt5555** [comment] 2020-06-23 00:39
I'm trying to run with PIO_REARR_COMM_MAX_PEND_REQ_COMP2I=64, but the code, which used to take about 5min to initialize, now takes over 30min (and thus times out in debug que).  
This was with the latest master - so I went back to the June 11 hash that I used initially.  It also takes > 30min to initialize.  

This is an issue that is probably unrelated to the COMP2I issue.  @dqwu  recommended moving all the inputdata into the parallel filesystem (I haven't tried that yet).  Pat, for your simulations, were you able to get it to run in < 30min?

**Comment by worleyph** [comment] 2020-06-23 00:49
Hi Mark, I believe that this is just due to system flakiness. My jobs went from 15 minutes to over 90 minutes and then back to 15 minutes a few days ago without changing anything. You might try moving inputdata to scratch, but, as Noel mentioned, this isn't always better. However, other than waiting for something to "magically" improve, you probably don't have anything else to try.

**Comment by mt5555** [comment] 2020-06-23 01:06
great, thanks

**Comment by mt5555** [comment] 2020-06-23 18:40
COMP2I=64 is working very well.  I went back to my original case, which is writing about 22GB, running on 1024 nodes:

original (no I/O):  init= 1090s.  + 708s/day
original (with I/O):   init: 1017s.  + 1662s/day
new (with I/O):   init: 2526 + 788s/day 

Note that the init time has gotten really bad - but this seems to be unrelated - as I reran one of my "original" cases and also got much slower init times.  

Question for @dqwu :  Above you posted some good results with a newer version of SCORPIO.    Do you think I could get better results with COMP2I=64 and this newer SCORPIO?

**Comment by worleyph** [comment] 2020-06-23 18:43
@mt5555 , I believe that @dqwu posted results using a slightly older version of SCORPIO, just before the PR that introduced the bug. This older version probably defaulted to COMP2I=64.

**Comment by dqwu** [comment] 2020-06-23 18:49
> @mt5555 , I believe that @dqwu posted results using a slightly older version of SCORPIO, just before the PR that introduced the bug. This older version probably defaulted to COMP2I=64.

I am using an old hash of E3SM, so it does not have latest CIME changes that introduced the bug. The scorpio version depends on the default release tag when "git submodule update --init" is called. I think the release tag is only updated occasionally by a PR to E3SM when next scorpio stable release becomes available.

**Comment by ndkeen** [comment] 2020-06-25 19:41
Note that I tried using setting `PIO_REARR_COMM_MAX_PEND_REQ_COMP2IO` with a common ne256 run on 128 nodes of Cori. Results are mixed.

Using scream repo of June 19th, I have 2 cases. `RQ0` refers to this value being 0 (current default), while `RQ64` is my explicitly setting it to 64.

```cori01% grep PIO_REARR_COMM_MAX_PEND_REQ_COMP2IO f.ne256pg2tri.s17-jun18.n0128t64x211121.nr.24s.nc00c.N144.RQ*/env_run.xml
f.ne256pg2tri.s17-jun18.n0128t64x211121.nr.24s.nc00c.N144.RQ0/env_run.xml:    <entry id="PIO_REARR_COMM_MAX_PEND_REQ_COMP2IO" value="0">
f.ne256pg2tri.s17-jun18.n0128t64x211121.nr.24s.nc00c.N144.RQ64/env_run.xml:    <entry id="PIO_REARR_COMM_MAX_PEND_REQ_COMP2IO" value="64">

I ran each case 3 times.
cori01% grep "Init Time" f.ne256pg2tri.s17-jun18.n0128t64x211121.nr.24s.nc00c.N144.RQ0/timing/*
f.ne256pg2tri.s17-jun18.n0128t64x211121.nr.24s.nc00c.N144.RQ0/timing/e3sm_timing.f.ne256pg2tri.s17-jun18.n0128t64x211121.nr.24s.nc00c.N144.RQ0.31993773.200622-195851:    Init Time   :    1670.364 seconds 
f.ne256pg2tri.s17-jun18.n0128t64x211121.nr.24s.nc00c.N144.RQ0/timing/e3sm_timing.f.ne256pg2tri.s17-jun18.n0128t64x211121.nr.24s.nc00c.N144.RQ0.32015630.200623-101903:    Init Time   :    1792.257 seconds 
f.ne256pg2tri.s17-jun18.n0128t64x211121.nr.24s.nc00c.N144.RQ0/timing/e3sm_timing.f.ne256pg2tri.s17-jun18.n0128t64x211121.nr.24s.nc00c.N144.RQ0.32017291.200623-121757:    Init Time   :    1481.432 seconds 
cori01% grep "Init Time" f.ne256pg2tri.s17-jun18.n0128t64x211121.nr.24s.nc00c.N144.RQ64/timing/*
f.ne256pg2tri.s17-jun18.n0128t64x211121.nr.24s.nc00c.N144.RQ64/timing/e3sm_timing.f.ne256pg2tri.s17-jun18.n0128t64x211121.nr.24s.nc00c.N144.RQ64.32014079.200623-093417:    Init Time   :    1400.689 seconds 
f.ne256pg2tri.s17-jun18.n0128t64x211121.nr.24s.nc00c.N144.RQ64/timing/e3sm_timing.f.ne256pg2tri.s17-jun18.n0128t64x211121.nr.24s.nc00c.N144.RQ64.32017298.200623-141941:    Init Time   :    1579.701 seconds 
f.ne256pg2tri.s17-jun18.n0128t64x211121.nr.24s.nc00c.N144.RQ64/timing/e3sm_timing.f.ne256pg2tri.s17-jun18.n0128t64x211121.nr.24s.nc00c.N144.RQ64.32021442.200624-015038:    Init Time   :    1707.635 seconds 

Note that the total time is fairly consistent between all 6 runs. These are not writing significant IO, however, it clearly looks like using 64 is an improvement in the total time (outside of init).

cori01% grep "TOT" f.ne256pg2tri.s17-jun18.n0128t64x211121.nr.24s.nc00c.N144.RQ0/timing/*
f.ne256pg2tri.s17-jun18.n0128t64x211121.nr.24s.nc00c.N144.RQ0/timing/e3sm_timing.f.ne256pg2tri.s17-jun18.n0128t64x211121.nr.24s.nc00c.N144.RQ0.31993773.200622-195851:    TOT Run Time:     446.324 seconds     2677.944 seconds/mday         0.09 myears/wday 
f.ne256pg2tri.s17-jun18.n0128t64x211121.nr.24s.nc00c.N144.RQ0/timing/e3sm_timing.f.ne256pg2tri.s17-jun18.n0128t64x211121.nr.24s.nc00c.N144.RQ0.32015630.200623-101903:    TOT Run Time:     447.436 seconds     2684.616 seconds/mday         0.09 myears/wday 
f.ne256pg2tri.s17-jun18.n0128t64x211121.nr.24s.nc00c.N144.RQ0/timing/e3sm_timing.f.ne256pg2tri.s17-jun18.n0128t64x211121.nr.24s.nc00c.N144.RQ0.32017291.200623-121757:    TOT Run Time:     447.718 seconds     2686.308 seconds/mday         0.09 myears/wday 
cori01% grep "TOT" f.ne256pg2tri.s17-jun18.n0128t64x211121.nr.24s.nc00c.N144.RQ64/timing/*
f.ne256pg2tri.s17-jun18.n0128t64x211121.nr.24s.nc00c.N144.RQ64/timing/e3sm_timing.f.ne256pg2tri.s17-jun18.n0128t64x211121.nr.24s.nc00c.N144.RQ64.32014079.200623-093417:    TOT Run Time:     421.025 seconds     2526.150 seconds/mday         0.09 myears/wday 
f.ne256pg2tri.s17-jun18.n0128t64x211121.nr.24s.nc00c.N144.RQ64/timing/e3sm_timing.f.ne256pg2tri.s17-jun18.n0128t64x211121.nr.24s.nc00c.N144.RQ64.32017298.200623-141941:    TOT Run Time:     412.616 seconds     2475.696 seconds/mday         0.10 myears/wday 
f.ne256pg2tri.s17-jun18.n0128t64x211121.nr.24s.nc00c.N144.RQ64/timing/e3sm_timing.f.ne256pg2tri.s17-jun18.n0128t64x211121.nr.24s.nc00c.N144.RQ64.32021442.200624-015038:    TOT Run Time:     422.551 seconds     2535.306 seconds/mday         0.09 myears/wday 

casedirs:
/global/cscratch1/sd/ndk/e3sm_scratch/cori-knl/s17-jun18/f.ne256pg2tri.s17-jun18.n0128t64x211121.nr.24s.nc00c.N144.RQ0
/global/cscratch1/sd/ndk/e3sm_scratch/cori-knl/s17-jun18/f.ne256pg2tri.s17-jun18.n0128t64x211121.nr.24s.nc00c.N144.RQ64


```

**Closed** 2021-03-01 16:33 UTC
Labels: SCORPIO, performance
