### ISSUE TITLE
Cime issue related to validate_variable_value

### ISSUE THREAD

**Issue by acme-y9s** [E3SM-Project/E3SM#2478] opened 2018-08-02 21:12 UTC
When I tried to write the land model output variable named 'M_LIVECROOTC_STORAGE_TO_LITTER_FIRE' to the history file (the default is inactive in history file), I got the error message 

ERROR: in validate_variable_value (package Build::Namelist): Variable name hist_fincl2 has a string element that is too long: 'M_LIVECROOTC_STORAGE_TO_LITTER_FIRE' 

Does anyone have any experiences for this?   Thanks!

**Comment by bishtgautam** [comment] 2018-08-02 22:05
Please give `bishtgautam/lnd/field-name branch` a try.

**Comment by acme-y9s** [comment] 2018-08-07 14:20
@bishtgautam  Thank you so much. I will try it!

**Comment by acme-y9s** [comment] 2018-08-09 18:10
@bishtgautam  That worked! Thanks

**Comment by rljacob** [comment] 2018-08-09 18:13
Leave this open until the problem is fixed on master.

**Closed** 2018-09-06 17:36 UTC
Labels: Land
