### ISSUE TITLE
ELM cmake configuration cannot find load files in FindPETSc.cmake, when 'CLM_USE_PETSC' is TRUE

### ISSUE THREAD

**Issue by fmyuan** [E3SM-Project/E3SM#3316] opened 2019-11-15 15:37 UTC
After ELM build switches from make to cmake, when 'CLM_USE_PETSC' is TRUE, the cmake configuration cannot successfully find PETSc package. The error message is like:
```
........
-- Configuring incomplete, errors occurred! 
See also "...../bld/lnd/obj/CMakeFiles/CMakeOutput.log".
CMake Error at ...../cime/src/CMake/FindPETSc.cmake:124 (include):
  include could not find load file:
    FindPackageMultipass
Call Stack (most recent call first):
  CMakeLists.txt:229 (find_package)
CMake Error at ....../cime/src/CMake/FindPETSc.cmake:125 (find_package_multipass):
  Unknown CMake command "find_package_multipass".
Call Stack (most recent call first):
  CMakeLists.txt:229 (find_package)
ERROR: CMake Error at ....../cime/src/CMake/FindPETSc.cmake:124 (include):
  include could not find load file:
    FindPackageMultipass
Call Stack (most recent call first):
  CMakeLists.txt:229 (find_package)
CMake Error at /Users/f9y/mygithub/ACME/cime/src/CMake/FindPETSc.cmake:125 (find_package_multipass):
  Unknown CMake command "find_package_multipass".
Call Stack (most recent call first):
  CMakeLists.txt:229 (find_package)
```

I think it's because the cmake module files for PETsc package were not ALL copied from Jed Brown's (see: https://github.com/jedbrown/cmake-modules). And some minor edits in cime/src/CMake/FindPETSc.cmake are also needed. So fixes, tested on ORNL CADES, may be like in branch:

 fmyuan/lnd/elm-pflotran
commit: [56557334afd8474e68c7b7289e018b2d42dd9b7d](https://github.com/E3SM-Project/E3SM/commit/56557334afd8474e68c7b7289e018b2d42dd9b7d)

**Comment by bishtgautam** [comment] 2019-11-15 16:09
@jqyin Since I don't have access to ORNL CADES, can this be assigned to you?

**Comment by rljacob** [comment] 2019-11-15 18:18
Do you have to be on ORNL CADES to reproduce the problem?  We don't officially support that platform.

**Comment by fmyuan** [comment] 2019-11-15 18:30
@rljacob  No. I think that, for whatever reason to use PETSc libraries available in any platform, it's not going to work with cmake.

**Comment by rljacob** [comment] 2019-11-15 18:31
Please share the create_newcase command and other steps to reproduce the problem.

**Comment by fmyuan** [comment] 2019-11-15 18:43
@rljacob 
1. should be no specific options for create_new_case. 
2. After create_new_case, ./case.setup may have issue not find 'PETSC_PATH', which upon platform's environmetal variables.
3. After ./case.setup, modify 'env_build.xml' for 'CLM_USE_PETSC' or 'USE_PETSC' to 'TRUE'
4. ./case.build then should stop when building CLM, due to this bug.

**Comment by rljacob** [comment] 2019-11-15 19:04
1. Maybe not but what case are you trying to build?

**Comment by fmyuan** [comment] 2019-11-15 19:22
I'm trying to use PETSc library for coupling PFLOTRAN to ELM. There was no specific create_new_case option for this. 
The real issue is that E3SM Makefile will try to include and to link PETSc headers and libs, when 'USE_PETSC' set to TRUE. Those will be provided by cmake configuration via ./component/CMakelist.txt, which actually calls module files in ./cime/src/CMake/. For PETSc package in that folder, only findPETSc.cmake exists while other files from Jed Brown's not.

**Closed** 2019-11-22 23:29 UTC
Labels: CIME, bug
