### ISSUE TITLE
Problems with run_e3sm

### ISSUE THREAD

**Issue by PeterCaldwell** [E3SM-Project/E3SM#2395] opened 2018-06-13 01:09 UTC
I just tried running run_e3sm.template.csh from today's master (6/12/18) and 
1). acme.exe needs to be replaced with e3sm.exe for using old_executable functionality.
2). something changed in the way this line is handled:

"case.submit --batch-args  --job-name=test --output=batch_output/cori-knl.master.test.ne30_oECv3_ICG.o%j"

which causes that line to fail with this error: 

 "ValueError: invalid interpolation syntax in ' --job-name=test --output=batch_output/cori-knl.master.test.ne30_oECv3_ICG.o%j ' at position 76"

The offending characters are "%j"... when I remove them, case.submit works fine. @cameronsmith1 - do you know what the intention of %j was? @mfdeakin-sandia  and @jgfouca  - do you know what changed in the treatment of this %j?

**Comment by jgfouca** [comment] 2018-06-13 16:21
@PeterCaldwell , %j is supposed to insert the job-id. Is that a python error? If so, you can provide the callstack?

**Comment by mfdeakin-sandia** [comment] 2018-06-13 17:07
Sorry for the delay on responding to the testing failures, I'll fix this today.

**Comment by PeterCaldwell** [comment] 2018-06-13 17:33
@jgfouca - my recollection is that the error was in python, but cori is down now so I can't look and when I try to run on edison I get "ERROR: module command /opt/modules/default/bin/modulecmd python load craype/2.5.12.3 craype-ivybridge failed with message:
craype(3):ERROR:105: Unable to locate a modulefile for 'craype/2.5.12.3'
p*(3):ERROR:105: Unable to locate a modulefile for 'craype-ivybridge'" ... @ndkeen - are there still known issues with edison?

**Comment by mfdeakin-sandia** [comment] 2018-06-19 21:21
Basically the issue is that `SafeConfigParser` (used directly by `case.submit`) is trying to do some parsing of the input, and responds badly to `%*` when we don't define them. I think that instead of using that, just using the defaults for `ConfigParser` would fix this? It doesn't crash when I do, at least

**Comment by cameronsmith1** [comment] 2018-06-19 22:05
Does it add some sort of unique identifier for the batch job without the %j, so that we don't get problems from multiple runs?

**Comment by ndkeen** [comment] 2018-06-19 22:12
The error on edison regarding that module version implies that your repo is not current as that should be fixed now.

And I posted a similar message on slack (June 7th) regarding the invalid interpolation issue.

**Comment by mfdeakin-sandia** [comment] 2018-06-19 23:09
@cameronsmith1 I'm pretty sure not, unfortunately

**Comment by cameronsmith1** [comment] 2018-06-19 23:22
Is there some other way we can get similar functionality?

**Comment by rljacob** [comment] 2018-06-19 23:44
What's the functionality that you want?

**Comment by cameronsmith1** [comment] 2018-06-19 23:49
We normally direct the output from a model batch job into a file.   And when we run a sequence of jobs it is useful to keep the output from each job, so we can check back for system problems later.   One easy and useful way to do this is to add the batch-job number to the filename of the log file.  That is what the %j does.    But apparently that isn't working anymore.

**Comment by mfdeakin-sandia** [comment] 2018-06-20 00:30
I have a fix for this which will go into CIME before the next merge, but I guess the simplest solution for now is to run `sed 's:SafeConfigParser:ConfigParser:' cime/scripts/Tools/case.submit`

**Comment by rljacob** [comment] 2018-06-20 01:47
Trying to sum up:  If you don't do anything, the batch system output will appear in a file called $CASE.run.$JOBID in the case directory (on edison).  The --output argument changes the default output file name and we want to be able to still have the $JOBID as  part of it.

**Comment by cameronsmith1** [comment] 2018-06-21 02:14
As I recall, the key reason was to change the directory the log files go into.   With long runs the case directory gets clogged up with the log files, so this puts them into a sub-directory.

**Closed** 2018-06-21 22:42 UTC
Labels: bug, minor, run_e3sm
