### ISSUE TITLE
negative litter fluxes to soil 

### ISSUE THREAD

**Issue by jinyuntang** [E3SM-Project/E3SM#2538] opened 2018-09-13 20:18 UTC
In some configurations (e.g., C-only) of the land bgc model, litter fluxes to soil are found occasionally to be negative. This is due to the lack of explicit constraint on the transfer fluxes between various litter pools in current code. When this is combined with machine roundoff error, given enough time of model integration, some vegetation pools become negative and then iterate with soil bgc pools and fluxes to amplify the negativity. The current code has some fix in the soil bgc pools to suppress the this positive feedback of negativity, but the root cause associated with litter flux is not addressed. This fix will address the root cause of this bug.

**Comment by jinyuntang** [comment] 2018-09-13 20:18
a fix is under testing.

**Comment by thorntonpe** [comment] 2018-09-13 20:30
@jinyuntang , does this impact all variants of the land BGC code?

**Comment by jinyuntang** [comment] 2018-09-13 20:40
@thorntonpe , theoretically, it is. Because the part needs change are shared to among CTC and ECA code. This seems to be the root cause why CNPrecision is needed.

**Comment by jinyuntang** [comment] 2018-12-06 23:34
@rljacob, am I unleashed to work on this?

**Comment by rljacob** [comment] 2018-12-06 23:44
I just like to make sure every issue has an assignee.

Is this being fixed by PR #2590?  Is this issue a duplicate of #2583 ?

**Comment by jinyuntang** [comment] 2018-12-06 23:49
@rljacob NO. The negative litter flux issue is a design level bug, and needs to add several subroutines to fix. I have that fixed in my branch, but if OK, I can migrate the fix to a branch derived from the most recent master.

**Comment by rljacob** [comment] 2018-12-06 23:52
Ok. The priority should be set by the BGC group leads since this is a BGC function.  @kvcalvin or @susburrows

**Comment by kvcalvin** [comment] 2018-12-07 19:19
@jinyuntang: I'll need more information on level of effort and how likely the error is to occur before deciding priority. Let's focus on the v1 simulations now and revisit this in January.

Also tagging @bpbond so he is aware.

**Comment by jinyun1tang** [comment] 2019-02-13 19:30
@susburrows , according to @kvcalvin , I will present the results of my exploration next CBGC call.  In short, I found it marginally affects CTC, and moderately affect ECA because of some unique feature differences in the vegetation dynamics. From there, we can make a decision on how to proceed in the short and long term.

**Comment by susburrows** [comment] 2019-02-13 19:37
OK, thanks for the update!

**Closed** 2019-06-20 17:48 UTC
Labels: Land, bug, non-BFB
