### ISSUE TITLE
create_test indexing into odict_keys incompatible with python3

### ISSUE THREAD

**Issue by brhillman** [E3SM-Project/E3SM#2800] opened 2019-03-13 15:23 UTC
It appears that something changed in `create_test` that has broken python 3 compatibility. The following command and error illustrates the problem:
```
(base) [bhillma@chama-login2 scripts (master)]$ ./create_test SMS_Ld1.ne4_ne4.FC5AV1C-L.sandiatoss3_intel.cam-rrtmgp
No project info available
Creating test directory /gpfs1/bhillma/acme_scratch/sandiatoss3/SMS_Ld1.ne4_ne4.FC5AV1C-L.sandiatoss3_intel.cam-rrtmgp.20190313_091732_rqer7i
RUNNING TESTS:
  SMS_Ld1.ne4_ne4.FC5AV1C-L.sandiatoss3_intel.cam-rrtmgp
Traceback (most recent call last):
  File "./create_test", line 640, in <module>
    _main_func(__doc__)
  File "./create_test", line 628, in _main_func
    mail_user, mail_type, wait_check_throughput, wait_check_memory, wait_ignore_namelists, wait_ignore_memleak, allow_pnl, non_local, single_exe)
  File "./create_test", line 584, in create_test
    wait_ignore_memleak=wait_ignore_memleak)
  File "/home/bhillma/codes/e3sm/branches/master/cime/scripts/Tools/../../scripts/lib/CIME/test_scheduler.py", line 964, in run_tests
    self._producer()
  File "/home/bhillma/codes/e3sm/branches/master/cime/scripts/Tools/../../scripts/lib/CIME/test_scheduler.py", line 855, in _producer
    procs_needed = self._get_procs_needed(test, next_phase, threads_in_flight)
  File "/home/bhillma/codes/e3sm/branches/master/cime/scripts/Tools/../../scripts/lib/CIME/test_scheduler.py", line 739, in _get_procs_needed
    first_test = self._tests.keys()[0]
TypeError: 'odict_keys' object does not support indexing
```
The problem appears to be in `cime/scripts/lib/CIME/test_scheduler.py`, where on line 739 the indexing operation `first_test = self._tests.keys()[0]` is performed. The version of python3 in my path does not like this (3.7.1) and complains that `odict_keys` objects do not support indexing. It appears that on ESMCI/cime master, there is a new method `self.first_test()` which simply casts the keys to a list before indexing. I assume this bug will be fixed in a merge from ESMCI/cime master? Or do we need to fix it in E3SM directly?

**Comment by jgfouca** [comment] 2019-03-13 17:09
Sorry about that, let me take a look.

**Comment by brhillman** [comment] 2019-03-13 17:15
@jgfouca no problem. Question though, do we test the CIME scripts with python3? Should we include a python3 test to make sure these things don't break?

**Comment by jgfouca** [comment] 2019-03-13 17:29
@brhillman , we have the results of Jenkins testing of CIME here:
https://my.cdash.org/index.php?project=CIME

... and the CIME travis CI does some basic testing of both py2 and 3. So we do test it. The testing of CIME on the E3SM side is much less rigorous, which is how this error slipped-in.

I am doing a CIME update today, but it's big and has some issues, so I'll just fix this manually.

**Comment by brhillman** [comment] 2019-03-13 17:31
Okay. No rush on my part, just wanted to point it out. It's easy enough for me to load a python2 module. Does it make sense to add a python3 test on the E3SM side? Excuse my ignorance on how CIME is pulled into E3SM, maybe that would be a pointless thing to do.

**Comment by jgfouca** [comment] 2019-03-13 17:36
@brhillman , I think the root cause is that sometimes I do the more expedient thing by doing CIME python work directly in E3SM/cime rather than doing it the "right" way (doing the work in ESMCI and then doing a CIME update to E3SM).

**Comment by jgfouca** [comment] 2019-03-13 17:39
> Okay. No rush on my part, just wanted to point it out.

Ok, then I'll just let this get fixed by the CIME upate:
https://github.com/E3SM-Project/E3SM/pull/2799

**Comment by brhillman** [comment] 2019-03-13 18:09
Sounds good, thanks!

**Closed** 2019-03-19 14:26 UTC
Labels: CIME, Testing
