### ISSUE TITLE
Edison run failing with Switch.pm error

### ISSUE THREAD

**Issue by susburrows** [E3SM-Project/E3SM#2539] opened 2018-09-16 00:28 UTC
Since yesterday afternoon, the model has been failing in at least some configurations with an error apparently related to a missing Perl module.  

Building from the run_e3sm_template.csh from current master fails with the following output in CaseStatus:

2018-09-15 17:05:23: case.run error 
ERROR: Command: '/global/u2/s/sburrows/E3SM-project/E3SM-codes/E3SM/components/mpas-seaice/bld/build-namelist -infile /scratch1/scratchdirs/sburrows/E3SM_simulations/default.default.A_WCYCL1850_template.ne4_oQU240/case_scripts/Buildconf/mpassiconf/cesm_namelist -caseroot /scratch1/scratchdirs/sburrows/E3SM_simulations/default.default.A_WCYCL1850_template.ne4_oQU240/case_scripts -casebuild /scratch1/scratchdirs/sburrows/E3SM_simulations/default.default.A_WCYCL1850_template.ne4_oQU240/case_scripts/Buildconf -cimeroot /global/u2/s/sburrows/E3SM-project/E3SM-codes/E3SM/cime -inst_string '' -decomp_prefix 'mpas-cice.graph.info.' -date_stamp '151209' -ice_grid 'oQU240' -ic_mode 'cold_start' -ice_bgc 'no_ice_bgc' -surface_mode 'free' -ntasks_ice '96' -ninst_ice '1'' failed with error '**Can't locate Switch.pm in @INC (you may need to install the Switch module)** (@INC contains: /usr/lib/perl5/site_perl/5.18.2/x86_64-linux-thread-multi /usr/lib/perl5/site_perl/5.18.2 /usr/lib/perl5/vendor_perl/5.18.2/x86_64-linux-thread-multi /usr/lib/perl5/vendor_perl/5.18.2 /usr/lib/perl5/5.18.2/x86_64-linux-thread-multi /usr/lib/perl5/5.18.2 /usr/lib/perl5/site_perl .) at /global/u2/s/sburrows/E3SM-project/E3SM-codes/E3SM/components/mpas-seaice/bld/build-namelist line 1495.
BEGIN failed--compilation aborted at /global/u2/s/sburrows/E3SM-project/E3SM-codes/E3SM/components/mpas-seaice/bld/build-namelist line 1495.' from dir '/scratch1/scratchdirs/sburrows/E3SM_simulations/default.default.A_WCYCL1850_template.ne4_oQU240/case_scripts/Buildconf/mpassiconf'

Two tests are failing in the last nightly acme_developer test with the same/similar error.  Logfiles are linked below.

ERS.f09_g16_g.MALISIA.edison_intel:
https://my.cdash.org/testDetails.php?test=42093503&build=1523329

ERS_Ld5.T62_oQU120.CMPASO-NYF.edison_intel:
https://my.cdash.org/testDetails.php?test=42093520&build=1523329

**Comment by susburrows** [comment] 2018-09-16 00:29
Tagging @kaabre , who initially encountered this error during test runs yesterday afternoon.

**Comment by susburrows** [comment] 2018-09-16 00:31
(Based on the error message, I think this has something to do with a missing perl module.  Since it also affects tests we have been doing on maint-1.1 branch and other tags, it may be a machine issue)

**Comment by Larofeticus** [comment] 2018-09-16 01:11
This is the result of a temporary issue on NERSCs part. We're adjusting the images used on compute nodes, and a few dependencies have slipped through the cracks.

A fix is planned for wednesday next week.

**Comment by susburrows** [comment] 2018-09-16 04:10
Awesome -- thanks for letting us know!

**Comment by susburrows** [comment] 2018-09-17 17:05
Hi Jon,

Thanks for the tip!  We’ll try that out as a workaround.

--Susannah

**Comment by jonbob** [comment] 2018-09-17 17:27
Hi Susannah —it has been working for us, so it should get it going again

On Sep 17, 2018, at 11:05 AM, susburrows <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Jon,

Thanks for the tip! We’ll try that out as a workaround.

--Susannah

**Comment by maltrud** [comment] 2018-09-17 17:32
> On Sep 17, 2018, at 11:27 AM, Jon Wolfe <notifications@github.com> wrote:
> 
> Hi Susannah —it has been working for us, so it should get it going again 

this worked for me this weekend after i started seeing failures on both cori and edison, so give it a try.  i was thinking of aliasing the command since it doesn’t fail until the jobs starts….
-mat

**Comment by susburrows** [comment] 2018-09-17 22:27
Thanks!  Looks like this is working for us, too.

--Susannah

**Comment by darincomeau** [comment] 2018-09-20 15:41
Has anyone heard from NERSC about a fix for this? The ./case.submit --skip-preview-namelist works for a single submission, but jobs still fail on resubmit (unless there's a way to force --skip-preview-namelist on resubmits as well?).

**Comment by dqwu** [comment] 2018-09-20 16:10
This issue is also reproducible on Cori. It seems that only compute nodes are affected.

On a login node, if we run the following perl command, there is no error.
`perl -MSwitch -e 1`

However, if you run this command on a compute node (haswell or knl), 
there is an error message like below:
```
salloc -N 1 -C haswell -q interactive -t 00:01:00
...
perl -MSwitch -e 1
Can't locate Switch.pm in @INC (you may need to install the Switch module) (@INC contains: /usr/lib/perl5/site_perl/5.18.2/x86_64-linux-thread-multi /usr/lib/perl5/site_perl/5.18.2 /usr/lib/perl5/vendor_perl/5.18.2/x86_64-linux-thread-multi /usr/lib/perl5/vendor_perl/5.18.2 /usr/lib/perl5/5.18.2/x86_64-linux-thread-multi /usr/lib/perl5/5.18.2 /usr/lib/perl5/site_perl .).
BEGIN failed--compilation aborted.
```

**Comment by maltrud** [comment] 2018-09-20 17:11
On Sep 20, 2018, at 9:44 AM, Darin Comeau <notifications@github.com<mailto:notifications@github.com>> wrote:


Has anyone heard from NERSC about a fix for this?

i heard that it will be address during the next DST (next week?).

**Comment by dqwu** [comment] 2018-09-20 17:14
It seems that /usr/lib/perl5/vendor_perl/5.18.2/ has different content on login nodes and compute nodes.

On login node it contains Switch.pm:
```
ls /usr/lib/perl5/vendor_perl/5.18.2/
Apache      Carp     Data    Error       File    HTTP     JSON.pm  Mail   RPC      Switch.pm  Time    X11   auto                     spamassassin-run.pod
Archive     Config   Date    Error.pm    Git     IO       LWP      Net    RRDp.pm  Test       URI     X500  i586-linux-thread-multi  x86_64-linux-thread-multi
Bootloader  Convert  Digest  Expect.pm   Git.pm  Immunix  LWP.pm   Parse  SUSE     Text       URI.pm  XML   lwpcook.pod              ycp.pm
Bundle      Crypt    Encode  Expect.pod  HTML    JSON     MIME     Path   Sub      Tie        WWW     YaST  lwptut.pod
```

On compute nodes it contains less files (no Switch.pm):
```
ls /usr/lib/perl5/vendor_perl/5.18.2/
Data	File  HTTP  LWP     Net      URI     WWW  aarch64-linux-thread-multi  lwpcook.pod  x86_64-linux-thread-multi
Encode	HTML  IO    LWP.pm  RRDp.pm  URI.pm  XML  auto			      lwptut.pod
```

**Comment by dqwu** [comment] 2018-09-20 20:19
@jayeshkrishna 
FYI, here is a simple workaround before NERSC fixes the Perl issue on compute nodes.

```
1) Download and install cpanminus in your home directory:
wget -O- http://cpanmin.us | perl - -l ~/perl5 App::cpanminus local::lib

2) Set the environment variables needed to use the local modules:
eval `perl -I ~/perl5/lib/perl5 -Mlocal::lib`

3) Install Switch.pm to ~/perl5/lib/perl5:
cpanm -f install Switch.pm

4) Edit ~/.bashrc.ext with a new line (edit ~/.kshrc.ext if you are not using bash)
eval `perl -I ~/perl5/lib/perl5 -Mlocal::lib`
```

When an E3SM case is running on compute nodes,  `@INC `contains ~/perl5/lib/perl5,
where Switch.pm can be located.

**Comment by ndkeen** [comment] 2018-09-21 16:57
Thanks @dqwu for this workaround, although I have not tried it yet. Based on earlier comments, I was under the impression this was a known issue at NERSC and would be resolved soon.

@tangq also found another software issue on edison compute nodes and I emailed NERSC.  The reply I got yesterday was:  

```
I am not sure the exact date when we get the fix. If you want to a workaround, you can try the following,
module -a use /global/common/software/nstaff/modulefiles
module load static_libs

before invoke the perl command. The static_libs module is just a copy of the /usr/lib64,/usr/bin from a login nodes. I am not sure if I have set the paths correctly. Please let me know if it works for you or not.

You can install the perl modules to your account if you prefer.
```

I have not tried this either, but @tangq let me know yesterday this helped him get around the imagemagick issue.

**Comment by ndkeen** [comment] 2018-12-07 01:48
Can anyone indicate if this is still an issue? I've certainly been able to run on edison.

**Comment by dqwu** [comment] 2018-12-07 14:31
@ndkeen 
I have tested it on a Cori (haswell node). Now /usr/lib/perl5/vendor_perl/5.18.2 contains Switch.pm,
and the command "perl -MSwitch -e 1" does not fail.
It seems that this issue has been fixed.

**Comment by ndkeen** [comment] 2021-03-26 18:13
Closing old issue

**Closed by ndkeen** 2021-03-26 18:13 UTC
Labels: Edison
