### ISSUE TITLE
memleak in ERP_Ld3.ne30_oECv3_ICG.A_WCYCL1850S.sandiatoss3_intel 

### ISSUE THREAD

**Issue by rljacob** [E3SM-Project/E3SM#3934] opened 2020-11-07 04:11 UTC
After https://github.com/ESMCI/cime/pull/3736 was merged to master in https://github.com/E3SM-Project/E3SM/pull/3891, the ERP_Ld3.ne30_oECv3_ICG.A_WCYCL1850S.sandiatoss3_intel  test started to fail with a memleak:

`2020-11-05 21:29:05: memleak detected, memory went from 3525.930000 to 4290.060000 in 1 days`

If this is real what caused it?   Also if its real, why just that case and not other coupled runs with that resolution?

**Comment by rljacob** [comment] 2020-11-07 04:14
We thought the memleak might be from PR #3885  which is fixed in PR #3932 but the code causing the memleak there isn't used in a regular coupled case.

**Comment by singhbalwinder** [comment] 2020-11-07 06:03
Yeah, I confirmed running a case that memleak fixed in #3932 is not used in FC5AV1C-L compset (which is used in WCYCL compset). So #3932 won't fix this issue.

Here are two more cases where I saw ERP failing with a memory leak in the past and we can still reproduce it:

@guangxinglin saw ERP failing with a memleak on Cori with maint-1.0 branch. I was able to reproduce it using an F case:
```
PASS ERP.ne4_ne4.FC5AV1C-L.cori-knl_intel CREATE_NEWCASE
PASS ERP.ne4_ne4.FC5AV1C-L.cori-knl_intel XML
PASS ERP.ne4_ne4.FC5AV1C-L.cori-knl_intel SETUP
PASS ERP.ne4_ne4.FC5AV1C-L.cori-knl_intel SHAREDLIB_BUILD time=645
PASS ERP.ne4_ne4.FC5AV1C-L.cori-knl_intel MODEL_BUILD time=1385
PASS ERP.ne4_ne4.FC5AV1C-L.cori-knl_intel SUBMIT
PASS ERP.ne4_ne4.FC5AV1C-L.cori-knl_intel RUN time=531
PASS ERP.ne4_ne4.FC5AV1C-L.cori-knl_intel COMPARE_base_rest
FAIL ERP.ne4_ne4.FC5AV1C-L.cori-knl_intel MEMLEAK memleak detected, memory went from 3258.000000 to 3740.000000 in 9 days
PASS ERP.ne4_ne4.FC5AV1C-L.cori-knl_intel SHORT_TERM_ARCHIVER
```
The above error is *not* reproducible on Compy. I was surprised to see it as it is a very old branch (v1 model). 

@AaronDonahue also saw tests failing with a memory leak with SCREAM tests and increased the tolerance to get a PASS. Those tests were also ERP tests.

Memleak is showing up only in the ERP tests so it might be related to threading. I asked @guangxinglin to run a PET test using maint-1.0 and there was no issue with that test. So it looks like a combination of threading and a restart run.

**Comment by worleyph** [comment] 2020-11-07 17:20
I tried ERP_Ld3.ne30_oECv3_ICG.A_WCYCL1850S.cori-knl_intel:

    FAIL ERP_Ld3.ne30_oECv3_ICG.A_WCYCL1850S.cori-knl_intel RUN time=633

but due to a misconfiguration of the PE layout for the second run:

     ERROR: Could not open block decomposition file for 167 blocks.
     CRITICAL ERROR: Filename: /global/cfs/cdirs/e3sm/inputdata/ocn/mpas-o/oEC60to30v3/mpas-o.graph.info.161222.part.167

FYI.

**Comment by amametjanov** [comment] 2020-11-13 05:19
> If this is real what caused it?

The cause is heavier restart write IO on PIO_ROOT, which by default is rank 0. It also shows up in the middle of un-threaded `ERS` tests for ultra-low-res and low-res runs. While a workaround of setting `TEST_MEMLEAK_TOLERANCE=0.25` or higher for sandiatoss3 (default is 0.1 or 10%) will avoid this issue, it will also mask other possible memleaks. My vote is to set PIO_ROOT to 1 for sandiatoss3 for this compset: see below.

Details:
Here is an example from 10-day runs of 44-node `ERS_Ld10.ne30_oECv3_ICG.A_WCYCL1850S.anvil_intel`, spike is at day 7:
```
$ zgrep "memory_write" cpl.log.267309.201112-190952.gz
 memory_write: model date =   00010101       0 memory =    3282.70 MB (highwater)       1135.48 MB (usage)  (pe=    0 comps= cpl ATM ICE GLC WAV IAC ESP)
 memory_write: model date =   00010102       0 memory =    3282.70 MB (highwater)       1139.41 MB (usage)  (pe=    0 comps= cpl ATM ICE GLC WAV IAC ESP)
 memory_write: model date =   00010103       0 memory =    3282.70 MB (highwater)       1140.07 MB (usage)  (pe=    0 comps= cpl ATM ICE GLC WAV IAC ESP)
 memory_write: model date =   00010104       0 memory =    3282.70 MB (highwater)       1140.36 MB (usage)  (pe=    0 comps= cpl ATM ICE GLC WAV IAC ESP)
 memory_write: model date =   00010105       0 memory =    3282.70 MB (highwater)       1140.53 MB (usage)  (pe=    0 comps= cpl ATM ICE GLC WAV IAC ESP)
 memory_write: model date =   00010106       0 memory =    3282.70 MB (highwater)       1140.64 MB (usage)  (pe=    0 comps= cpl ATM ICE GLC WAV IAC ESP)
 memory_write: model date =   00010107       0 memory =    3531.07 MB (highwater)       1376.66 MB (usage)  (pe=    0 comps= cpl ATM ICE GLC WAV IAC ESP)
 memory_write: model date =   00010108       0 memory =    3531.07 MB (highwater)       1376.74 MB (usage)  (pe=    0 comps= cpl ATM ICE GLC WAV IAC ESP)
 memory_write: model date =   00010109       0 memory =    3531.07 MB (highwater)       1376.74 MB (usage)  (pe=    0 comps= cpl ATM ICE GLC WAV IAC ESP)
 memory_write: model date =   00010110       0 memory =    3531.07 MB (highwater)       1376.75 MB (usage)  (pe=    0 comps= cpl ATM ICE GLC WAV IAC ESP)
 memory_write: model date =   00010111       0 memory =    3531.07 MB (highwater)       1377.34 MB (usage)  (pe=    0 comps= cpl ATM ICE GLC WAV IAC ESP)
```
Memory footprint of LND and ROF root process:
```
$ zgrep "memory_write" e3sm.log.267309.201112-190952.gz | grep "^1296:"
1296:  memory_write: model date =   00010101       0 memory =    2822.89 MB (highwater)       1077.70 MB (usage)  (pe= 1296 comps= ATM LND)
1296:  memory_write: model date =   00010102       0 memory =    2825.34 MB (highwater)       1086.59 MB (usage)  (pe= 1296 comps= ATM LND)
1296:  memory_write: model date =   00010103       0 memory =    2825.34 MB (highwater)       1086.60 MB (usage)  (pe= 1296 comps= ATM LND)
1296:  memory_write: model date =   00010104       0 memory =    2825.34 MB (highwater)       1086.60 MB (usage)  (pe= 1296 comps= ATM LND)
1296:  memory_write: model date =   00010105       0 memory =    2825.34 MB (highwater)       1086.60 MB (usage)  (pe= 1296 comps= ATM LND)
1296:  memory_write: model date =   00010106       0 memory =    2825.34 MB (highwater)       1086.60 MB (usage)  (pe= 1296 comps= ATM LND)
1296:  memory_write: model date =   00010107       0 memory =    3633.93 MB (highwater)       1944.44 MB (usage)  (pe= 1296 comps= ATM LND)
1296:  memory_write: model date =   00010108       0 memory =    3633.93 MB (highwater)       1944.44 MB (usage)  (pe= 1296 comps= ATM LND)
1296:  memory_write: model date =   00010109       0 memory =    3633.93 MB (highwater)       1944.44 MB (usage)  (pe= 1296 comps= ATM LND)
1296:  memory_write: model date =   00010110       0 memory =    3633.93 MB (highwater)       1944.45 MB (usage)  (pe= 1296 comps= ATM LND)
1296:  memory_write: model date =   00010111       0 memory =    3633.93 MB (highwater)       1944.45 MB (usage)  (pe= 1296 comps= ATM LND)
```
And OCN rootpe:
```
$ zgrep "memory_write" e3sm.log.267309.201112-190952.gz | grep "^1368:"
1368:  memory_write: model date =   00010101       0 memory =    2004.50 MB (highwater)        949.86 MB (usage)  (pe= 1368 comps= OCN)
1368:  memory_write: model date =   00010102       0 memory =    2025.68 MB (highwater)       1012.38 MB (usage)  (pe= 1368 comps= OCN)
1368:  memory_write: model date =   00010103       0 memory =    2039.17 MB (highwater)       1026.10 MB (usage)  (pe= 1368 comps= OCN)
1368:  memory_write: model date =   00010104       0 memory =    2039.17 MB (highwater)       1026.11 MB (usage)  (pe= 1368 comps= OCN)
1368:  memory_write: model date =   00010105       0 memory =    2039.17 MB (highwater)       1026.12 MB (usage)  (pe= 1368 comps= OCN)
1368:  memory_write: model date =   00010106       0 memory =    2067.24 MB (highwater)       1036.64 MB (usage)  (pe= 1368 comps= OCN)
1368:  memory_write: model date =   00010107       0 memory =    2318.16 MB (highwater)       1299.52 MB (usage)  (pe= 1368 comps= OCN)
1368:  memory_write: model date =   00010108       0 memory =    2318.16 MB (highwater)       1299.52 MB (usage)  (pe= 1368 comps= OCN)
1368:  memory_write: model date =   00010109       0 memory =    2318.16 MB (highwater)       1299.52 MB (usage)  (pe= 1368 comps= OCN)
1368:  memory_write: model date =   00010110       0 memory =    2318.16 MB (highwater)       1299.52 MB (usage)  (pe= 1368 comps= OCN)
1368:  memory_write: model date =   00010111       0 memory =    2318.16 MB (highwater)       1299.55 MB (usage)  (pe= 1368 comps= OCN)
```

And for single-node run of `ERS_Ld10.ne4_oQU240.A_WCYCL1850.anvil_intel` to check for any leaks in specific components, first CPL rootpe:
```
$ zgrep "memory_write" cpl.log.267310.201112-191208.gz
 memory_write: model date =   00010101       0 memory =     656.40 MB (highwater)        154.10 MB (usage)  (pe=    0 comps= cpl GLC WA
V IAC ESP)
 memory_write: model date =   00010102       0 memory =     656.40 MB (highwater)        155.17 MB (usage)  (pe=    0 comps= cpl GLC WA
V IAC ESP)
 memory_write: model date =   00010103       0 memory =     656.40 MB (highwater)        155.40 MB (usage)  (pe=    0 comps= cpl GLC WA
V IAC ESP)
 memory_write: model date =   00010104       0 memory =     656.40 MB (highwater)        155.55 MB (usage)  (pe=    0 comps= cpl GLC WA
V IAC ESP)
 memory_write: model date =   00010105       0 memory =     656.40 MB (highwater)        155.65 MB (usage)  (pe=    0 comps= cpl GLC WA
V IAC ESP)
 memory_write: model date =   00010106       0 memory =     656.40 MB (highwater)        155.70 MB (usage)  (pe=    0 comps= cpl GLC WA
V IAC ESP)
 memory_write: model date =   00010107       0 memory =     687.50 MB (highwater)        189.58 MB (usage)  (pe=    0 comps= cpl GLC WA
V IAC ESP)
 memory_write: model date =   00010108       0 memory =     687.50 MB (highwater)        189.61 MB (usage)  (pe=    0 comps= cpl GLC WA
V IAC ESP)
 memory_write: model date =   00010109       0 memory =     687.50 MB (highwater)        189.63 MB (usage)  (pe=    0 comps= cpl GLC WA
V IAC ESP)
 memory_write: model date =   00010110       0 memory =     687.50 MB (highwater)        189.68 MB (usage)  (pe=    0 comps= cpl GLC WA
V IAC ESP)
 memory_write: model date =   00010111       0 memory =     706.12 MB (highwater)        208.37 MB (usage)  (pe=    0 comps= cpl GLC WAV IAC ESP)
```
ATM rootpe:
```
$ zgrep "memory_write" e3sm.log.267310.201112-191208.gz | grep "^ 2:"
 2:  memory_write: model date =   00010101       0 memory =    2066.76 MB (highwater)        699.62 MB (usage)  (pe=    2 comps= ATM)
 2:  memory_write: model date =   00010102       0 memory =    2068.11 MB (highwater)        735.63 MB (usage)  (pe=    2 comps= ATM)
 2:  memory_write: model date =   00010103       0 memory =    2068.54 MB (highwater)        736.12 MB (usage)  (pe=    2 comps= ATM)
 2:  memory_write: model date =   00010104       0 memory =    2068.82 MB (highwater)        736.48 MB (usage)  (pe=    2 comps= ATM)
 2:  memory_write: model date =   00010105       0 memory =    2069.27 MB (highwater)        736.89 MB (usage)  (pe=    2 comps= ATM)
 2:  memory_write: model date =   00010106       0 memory =    2069.71 MB (highwater)        737.36 MB (usage)  (pe=    2 comps= ATM)
 2:  memory_write: model date =   00010107       0 memory =    2122.47 MB (highwater)        787.54 MB (usage)  (pe=    2 comps= ATM)
 2:  memory_write: model date =   00010108       0 memory =    2122.47 MB (highwater)        787.58 MB (usage)  (pe=    2 comps= ATM)
 2:  memory_write: model date =   00010109       0 memory =    2122.47 MB (highwater)        787.58 MB (usage)  (pe=    2 comps= ATM)
 2:  memory_write: model date =   00010110       0 memory =    2122.47 MB (highwater)        787.58 MB (usage)  (pe=    2 comps= ATM)
 2:  memory_write: model date =   00010111       0 memory =    2122.47 MB (highwater)        787.58 MB (usage)  (pe=    2 comps= ATM)
```
ICE rootpe:
```
$ zgrep "memory_write" e3sm.log.267310.201112-191208.gz | grep "^ 4:"
 4:  memory_write: model date =   00010101       0 memory =    1729.25 MB (highwater)       1098.41 MB (usage)  (pe=    4 comps= ICE)
 4:  memory_write: model date =   00010102       0 memory =    1754.05 MB (highwater)       1108.38 MB (usage)  (pe=    4 comps= ICE)
 4:  memory_write: model date =   00010103       0 memory =    1769.39 MB (highwater)       1123.83 MB (usage)  (pe=    4 comps= ICE)
 4:  memory_write: model date =   00010104       0 memory =    1769.39 MB (highwater)       1123.88 MB (usage)  (pe=    4 comps= ICE)
 4:  memory_write: model date =   00010105       0 memory =    1769.39 MB (highwater)       1123.93 MB (usage)  (pe=    4 comps= ICE)
 4:  memory_write: model date =   00010106       0 memory =    1769.39 MB (highwater)       1123.96 MB (usage)  (pe=    4 comps= ICE)
 4:  memory_write: model date =   00010107       0 memory =    1863.77 MB (highwater)       1177.49 MB (usage)  (pe=    4 comps= ICE)
 4:  memory_write: model date =   00010108       0 memory =    1879.11 MB (highwater)       1192.86 MB (usage)  (pe=    4 comps= ICE)
 4:  memory_write: model date =   00010109       0 memory =    1879.11 MB (highwater)       1192.89 MB (usage)  (pe=    4 comps= ICE)
 4:  memory_write: model date =   00010110       0 memory =    1879.11 MB (highwater)       1192.90 MB (usage)  (pe=    4 comps= ICE)
 4:  memory_write: model date =   00010111       0 memory =    1879.11 MB (highwater)       1192.92 MB (usage)  (pe=    4 comps= ICE)
```
LND rootpe:
```
$ zgrep "memory_write" e3sm.log.267310.201112-191208.gz | grep "^ 6:"
 6:  memory_write: model date =   00010101       0 memory =     784.24 MB (highwater)        218.66 MB (usage)  (pe=    6 comps= LND)
 6:  memory_write: model date =   00010102       0 memory =     795.83 MB (highwater)        239.03 MB (usage)  (pe=    6 comps= LND)
 6:  memory_write: model date =   00010103       0 memory =     795.83 MB (highwater)        239.06 MB (usage)  (pe=    6 comps= LND)
 6:  memory_write: model date =   00010104       0 memory =     795.83 MB (highwater)        239.09 MB (usage)  (pe=    6 comps= LND)
 6:  memory_write: model date =   00010105       0 memory =     795.83 MB (highwater)        239.11 MB (usage)  (pe=    6 comps= LND)
 6:  memory_write: model date =   00010106       0 memory =     795.83 MB (highwater)        239.13 MB (usage)  (pe=    6 comps= LND)
 6:  memory_write: model date =   00010107       0 memory =     839.82 MB (highwater)        282.93 MB (usage)  (pe=    6 comps= LND)
 6:  memory_write: model date =   00010108       0 memory =     839.82 MB (highwater)        282.96 MB (usage)  (pe=    6 comps= LND)
 6:  memory_write: model date =   00010109       0 memory =     839.82 MB (highwater)        282.98 MB (usage)  (pe=    6 comps= LND)
 6:  memory_write: model date =   00010110       0 memory =     839.82 MB (highwater)        282.98 MB (usage)  (pe=    6 comps= LND)
 6:  memory_write: model date =   00010111       0 memory =     839.82 MB (highwater)        282.98 MB (usage)  (pe=    6 comps= LND)
```
OCN rootpe:
```
$ zgrep "memory_write" e3sm.log.267310.201112-191208.gz | grep "^10:"
10:  memory_write: model date =   00010101       0 memory =    1317.45 MB (highwater)        794.55 MB (usage)  (pe=   10 comps= OCN)
10:  memory_write: model date =   00010102       0 memory =    1375.51 MB (highwater)        854.60 MB (usage)  (pe=   10 comps= OCN)
10:  memory_write: model date =   00010103       0 memory =    1384.21 MB (highwater)        863.42 MB (usage)  (pe=   10 comps= OCN)
10:  memory_write: model date =   00010104       0 memory =    1384.21 MB (highwater)        863.49 MB (usage)  (pe=   10 comps= OCN)
10:  memory_write: model date =   00010105       0 memory =    1384.21 MB (highwater)        863.57 MB (usage)  (pe=   10 comps= OCN)
10:  memory_write: model date =   00010106       0 memory =    1387.37 MB (highwater)        866.48 MB (usage)  (pe=   10 comps= OCN)
10:  memory_write: model date =   00010107       0 memory =    1532.56 MB (highwater)        958.16 MB (usage)  (pe=   10 comps= OCN)
10:  memory_write: model date =   00010108       0 memory =    1564.04 MB (highwater)        989.52 MB (usage)  (pe=   10 comps= OCN)
10:  memory_write: model date =   00010109       0 memory =    1564.04 MB (highwater)        989.54 MB (usage)  (pe=   10 comps= OCN)
10:  memory_write: model date =   00010110       0 memory =    1564.04 MB (highwater)        989.56 MB (usage)  (pe=   10 comps= OCN)
10:  memory_write: model date =   00010111       0 memory =    1564.04 MB (highwater)        989.57 MB (usage)  (pe=   10 comps= OCN)
```

The spike must've always been there before and the two merges on 2020-oct-22 pushed the spike above 10%.
An `ERS_Ld10.ne30_oECv3_ICG.A_WCYCL1850S.anvil_intel` run with hash `934a7e658` from the day before (2020-oct-21):
```
$ zgrep "memory_write" cpl.log.267400.201112-214506.gz
 memory_write: model date =   00010102       0 memory =    3279.15 MB (highwater)       1140.12 MB (usage)  (pe=    0 comps= cpl ATM ICE GLC WAV IAC ESP)
 memory_write: model date =   00010103       0 memory =    3279.15 MB (highwater)       1140.79 MB (usage)  (pe=    0 comps= cpl ATM ICE GLC WAV IAC ESP)
 memory_write: model date =   00010104       0 memory =    3279.15 MB (highwater)       1141.07 MB (usage)  (pe=    0 comps= cpl ATM ICE GLC WAV IAC ESP)
 memory_write: model date =   00010105       0 memory =    3279.15 MB (highwater)       1141.24 MB (usage)  (pe=    0 comps= cpl ATM ICE GLC WAV IAC ESP)
 memory_write: model date =   00010106       0 memory =    3279.15 MB (highwater)       1141.35 MB (usage)  (pe=    0 comps= cpl ATM ICE GLC WAV IAC ESP)
 memory_write: model date =   00010107       0 memory =    3527.43 MB (highwater)       1378.71 MB (usage)  (pe=    0 comps= cpl ATM ICE GLC WAV IAC ESP)
 memory_write: model date =   00010108       0 memory =    3527.43 MB (highwater)       1378.72 MB (usage)  (pe=    0 comps= cpl ATM ICE GLC WAV IAC ESP)
 memory_write: model date =   00010109       0 memory =    3527.43 MB (highwater)       1378.72 MB (usage)  (pe=    0 comps= cpl ATM ICE GLC WAV IAC ESP)
 memory_write: model date =   00010110       0 memory =    3527.43 MB (highwater)       1378.73 MB (usage)  (pe=    0 comps= cpl ATM ICE GLC WAV IAC ESP)
 memory_write: model date =   00010111       0 memory =    3527.43 MB (highwater)       1379.25 MB (usage)  (pe=    0 comps= cpl ATM ICE GLC WAV IAC ESP)
```
LND and ROF rootpe:
```
$ zgrep "memory_write" e3sm.log.267400.201112-214506.gz |grep "^1296:"
1296:  memory_write: model date =   00010102       0 memory =    2824.15 MB (highwater)       1076.59 MB (usage)  (pe= 1296 comps= ATM LND)
1296:  memory_write: model date =   00010103       0 memory =    2824.15 MB (highwater)       1076.60 MB (usage)  (pe= 1296 comps= ATM LND)
1296:  memory_write: model date =   00010104       0 memory =    2824.15 MB (highwater)       1076.60 MB (usage)  (pe= 1296 comps= ATM LND)
1296:  memory_write: model date =   00010105       0 memory =    2824.15 MB (highwater)       1076.61 MB (usage)  (pe= 1296 comps= ATM LND)
1296:  memory_write: model date =   00010106       0 memory =    2824.15 MB (highwater)       1076.61 MB (usage)  (pe= 1296 comps= ATM LND)
1296:  memory_write: model date =   00010107       0 memory =    3632.59 MB (highwater)       1933.35 MB (usage)  (pe= 1296 comps= ATM LND)
1296:  memory_write: model date =   00010108       0 memory =    3632.59 MB (highwater)       1933.35 MB (usage)  (pe= 1296 comps= ATM LND)
1296:  memory_write: model date =   00010109       0 memory =    3632.59 MB (highwater)       1933.35 MB (usage)  (pe= 1296 comps= ATM LND)
1296:  memory_write: model date =   00010110       0 memory =    3632.59 MB (highwater)       1933.35 MB (usage)  (pe= 1296 comps= ATM LND)
1296:  memory_write: model date =   00010111       0 memory =    3632.59 MB (highwater)       1933.35 MB (usage)  (pe= 1296 comps= ATM LND)
```
OCN roote:
```
$ zgrep "memory_write" e3sm.log.267400.201112-214506.gz |grep "^1368:"
1368:  memory_write: model date =   00010102       0 memory =    2024.09 MB (highwater)       1002.32 MB (usage)  (pe= 1368 comps= OCN)
1368:  memory_write: model date =   00010103       0 memory =    2037.64 MB (highwater)       1015.50 MB (usage)  (pe= 1368 comps= OCN)
1368:  memory_write: model date =   00010104       0 memory =    2037.64 MB (highwater)       1015.51 MB (usage)  (pe= 1368 comps= OCN)
1368:  memory_write: model date =   00010105       0 memory =    2037.64 MB (highwater)       1015.52 MB (usage)  (pe= 1368 comps= OCN)
1368:  memory_write: model date =   00010106       0 memory =    2065.71 MB (highwater)       1026.00 MB (usage)  (pe= 1368 comps= OCN)
1368:  memory_write: model date =   00010107       0 memory =    2316.63 MB (highwater)       1278.20 MB (usage)  (pe= 1368 comps= OCN)
1368:  memory_write: model date =   00010108       0 memory =    2316.63 MB (highwater)       1278.45 MB (usage)  (pe= 1368 comps= OCN)
1368:  memory_write: model date =   00010109       0 memory =    2316.63 MB (highwater)       1278.45 MB (usage)  (pe= 1368 comps= OCN)
1368:  memory_write: model date =   00010110       0 memory =    2316.63 MB (highwater)       1278.45 MB (usage)  (pe= 1368 comps= OCN)
1368:  memory_write: model date =   00010111       0 memory =    2316.63 MB (highwater)       1278.47 MB (usage)  (pe= 1368 comps= OCN)
```
So, a 7.571% (=3527.43/3279.15) spike on Oct 21 and a 7.566% (=3531.07/3282.70) spike for Nov 12 hash `2cdd0cce93`.
But, sandiatoss3 pe-layout is 128x1 (8 nodes) at rootpe=0 for all components, making restart write memory spike bigger.

To modify PIO_ROOT:
```
diff --git a/cime_config/machines/config_pio.xml b/cime_config/machines/config_pio.xml
index dc239b37e2..2913686c1c 100644
--- a/cime_config/machines/config_pio.xml
+++ b/cime_config/machines/config_pio.xml
@@ -37,6 +37,7 @@
   <entry id="PIO_ROOT">
     <values>
       <value>0</value>
+      <value mach="anvil" compset=".*EAM.+MPAS.*">1</value>
     </values>
   </entry>
```
And resulting mem-logs of `ERS_Ld10.ne30_oECv3_ICG.A_WCYCL1850S.anvil_intel`:
```
$ zgrep "memory_write" cpl.log.267403.201112-224151.gz 
 memory_write: model date =   00010101       0 memory =    1929.26 MB (highwater)        960.77 MB (usage)  (pe=    0 comps= cpl ATM ICE GLC WAV IAC ESP)
 memory_write: model date =   00010102       0 memory =    1929.26 MB (highwater)        965.56 MB (usage)  (pe=    0 comps= cpl ATM ICE GLC WAV IAC ESP)
 memory_write: model date =   00010103       0 memory =    1929.26 MB (highwater)        966.82 MB (usage)  (pe=    0 comps= cpl ATM ICE GLC WAV IAC ESP)
 memory_write: model date =   00010104       0 memory =    1929.26 MB (highwater)        967.46 MB (usage)  (pe=    0 comps= cpl ATM ICE GLC WAV IAC ESP)
 memory_write: model date =   00010105       0 memory =    1929.26 MB (highwater)        967.84 MB (usage)  (pe=    0 comps= cpl ATM ICE GLC WAV IAC ESP)
 memory_write: model date =   00010106       0 memory =    1929.26 MB (highwater)        968.09 MB (usage)  (pe=    0 comps= cpl ATM ICE GLC WAV IAC ESP)
 memory_write: model date =   00010107       0 memory =    1929.26 MB (highwater)        968.62 MB (usage)  (pe=    0 comps= cpl ATM ICE GLC WAV IAC ESP)
 memory_write: model date =   00010108       0 memory =    1929.26 MB (highwater)        968.78 MB (usage)  (pe=    0 comps= cpl ATM ICE GLC WAV IAC ESP)
 memory_write: model date =   00010109       0 memory =    1929.26 MB (highwater)        968.90 MB (usage)  (pe=    0 comps= cpl ATM ICE GLC WAV IAC ESP)
 memory_write: model date =   00010110       0 memory =    1929.26 MB (highwater)        968.99 MB (usage)  (pe=    0 comps= cpl ATM ICE GLC WAV IAC ESP)
 memory_write: model date =   00010111       0 memory =    1929.26 MB (highwater)        969.10 MB (usage)  (pe=    0 comps= cpl ATM ICE GLC WAV IAC ESP)
```
LND, ROF:
```
$ zgrep "memory_write" e3sm.log.267403.201112-224151.gz  | grep "^1296:"
1296:  memory_write: model date =   00010101       0 memory =    1872.66 MB (highwater)        917.23 MB (usage)  (pe= 1296 comps= ATM LND)
1296:  memory_write: model date =   00010102       0 memory =    1875.10 MB (highwater)        920.32 MB (usage)  (pe= 1296 comps= ATM LND)
1296:  memory_write: model date =   00010103       0 memory =    1875.10 MB (highwater)        920.37 MB (usage)  (pe= 1296 comps= ATM LND)
1296:  memory_write: model date =   00010104       0 memory =    1875.10 MB (highwater)        920.42 MB (usage)  (pe= 1296 comps= ATM LND)
1296:  memory_write: model date =   00010105       0 memory =    1875.10 MB (highwater)        920.48 MB (usage)  (pe= 1296 comps= ATM LND)
1296:  memory_write: model date =   00010106       0 memory =    1875.10 MB (highwater)        920.55 MB (usage)  (pe= 1296 comps= ATM LND)
1296:  memory_write: model date =   00010107       0 memory =    1875.10 MB (highwater)        921.25 MB (usage)  (pe= 1296 comps= ATM LND)
1296:  memory_write: model date =   00010108       0 memory =    1875.10 MB (highwater)        921.30 MB (usage)  (pe= 1296 comps= ATM LND)
1296:  memory_write: model date =   00010109       0 memory =    1875.10 MB (highwater)        921.35 MB (usage)  (pe= 1296 comps= ATM LND)
1296:  memory_write: model date =   00010110       0 memory =    1875.10 MB (highwater)        921.39 MB (usage)  (pe= 1296 comps= ATM LND)
1296:  memory_write: model date =   00010111       0 memory =    1875.10 MB (highwater)        921.44 MB (usage)  (pe= 1296 comps= ATM LND)
```
OCN:
```
$ zgrep "memory_write" e3sm.log.267403.201112-224151.gz  | grep "^1368:"
1368:  memory_write: model date =   00010101       0 memory =    1654.03 MB (highwater)        641.77 MB (usage)  (pe= 1368 comps= OCN)
1368:  memory_write: model date =   00010102       0 memory =    1654.04 MB (highwater)        680.34 MB (usage)  (pe= 1368 comps= OCN)
1368:  memory_write: model date =   00010103       0 memory =    1656.44 MB (highwater)        682.45 MB (usage)  (pe= 1368 comps= OCN)
1368:  memory_write: model date =   00010104       0 memory =    1656.44 MB (highwater)        682.47 MB (usage)  (pe= 1368 comps= OCN)
1368:  memory_write: model date =   00010105       0 memory =    1656.44 MB (highwater)        682.51 MB (usage)  (pe= 1368 comps= OCN)
1368:  memory_write: model date =   00010106       0 memory =    1656.44 MB (highwater)        682.61 MB (usage)  (pe= 1368 comps= OCN)
1368:  memory_write: model date =   00010107       0 memory =    1678.68 MB (highwater)        720.77 MB (usage)  (pe= 1368 comps= OCN)
1368:  memory_write: model date =   00010108       0 memory =    1692.30 MB (highwater)        734.00 MB (usage)  (pe= 1368 comps= OCN)
1368:  memory_write: model date =   00010109       0 memory =    1692.30 MB (highwater)        733.45 MB (usage)  (pe= 1368 comps= OCN)
1368:  memory_write: model date =   00010110       0 memory =    1692.30 MB (highwater)        733.45 MB (usage)  (pe= 1368 comps= OCN)
1368:  memory_write: model date =   00010111       0 memory =    1692.30 MB (highwater)        733.45 MB (usage)  (pe= 1368 comps= OCN)
```
So, down from 7.566% to at most 1.342% (in OCN).

Thoughts?

**Closed** 2020-11-20 19:30 UTC
Labels: Coupler, Testing
