### ISSUE TITLE
Should IO formats be limited to netcdf and pnetcdf?

### ISSUE THREAD

**Issue by amametjanov** [E3SM-Project/E3SM#2292] opened 2018-04-18 23:26 UTC
Support for netcdf4p file format varies across systems: see issues E3SM-Project/E3SM#1970 and E3SM-Project/E3SM#2048. Rather than loading netcdf + hdf5-parallel modules, which can then lead to reads/writes in netcdf4p format, proposed combination is netcdf (without hdf5) and pnetcdf. This could simplify software environment issues.

**Comment by mt5555** [comment] 2018-04-21 23:15
Could we support reading netcdf4 files if we expand the PIO interface to allow us to specify which library to use based on filename?  IIRC, the problem is that we want to use the pnetcdf library for writing and most read operations, but pnetcdf cant read netcdf4/hdf5 files.

**Comment by jayeshkrishna** [comment] 2018-04-23 14:59
Sorry for being late to this discussion. We can continue supporting netcdf4 and netcdf4p, but maybe we can limit the number of machines we support these features on?
 The issue with netcdf4p (parallel I/O using netcdf) is that the stability depends on the version compatibility of netcdf and hdf5 libraries (there are no documents AFAIK that enumerate this compatibility scenarios). We have observed that with some version combinations of netcdf and hdf5 libraries some PIO tests hang (while others succeed). So supporting netcdf4p on all machines will take up resources (installing/debugging etc).
 I have not encountered a scenario yet where netcdf4p performs better than pnetcdf. All of our tests indicate that pnetcdf outperforms netcdf4p+hdf5 for E3SM I/O. However like @mt5555 noted pnetcdf currently cannot directly read NetCDF4 files.
 Another feature that has been introduced in NetCDF 4.1+ is to use PnetCDF instead of HDF5 for parallel I/O (but won't help with reading data already in NetCDF4 format, written out using NetCDF+HDF5). Also we haven't tested this setup extensively to know all the possible issues with it.

**Comment by rljacob** [comment] 2018-07-24 17:11
Decision on this issue is here: https://acme-climate.atlassian.net/wiki/spaces/EIDMG/pages/769130507/Picking+a+netcdf+type+for+all+input+files

**Comment by wkliao** [comment] 2018-07-30 17:50
Too bad the URL is not open to public.
As a PnetCDF developer, I am interested in learning the decision :(

**Comment by rljacob** [comment] 2018-07-30 18:12
That is better called the "internal discussion" page.  When we reach a decision, we'll update this issue.

**Comment by rljacob** [comment] 2019-07-17 15:00
We decided that all input files will be in "netcdf3 classic" format.

**Closed by rljacob** 2019-07-17 15:00 UTC
Labels: question
