### ISSUE TITLE
Build fails invoking generate_cice_decomp.pl

### ISSUE THREAD

**Issue by pochedls** [E3SM-Project/E3SM#2650] opened 2018-12-04 17:26 UTC
In building E3SM on a non-supported machine (main branch from Nov. 19, 2018), I received the following error:

> ERROR: Command: './generate_cice_decomp.pl -ccsmroot /g/g14/pochedls/e3sm/code/maint_1_0 -res ne30np4 -nx 48602 -ny 1 -nproc 800.0 -thrds 1 -output all' failed with error 'b'Value "800.0" invalid for option nproc (number expected)\nSYNOPSIS\n     generate_cice_decomp.pl [options]\nOPTIONS\n     -ccsmroot <path>               Full pathname for ccsmroot\n                                    (required)\n     -nproc <number>      (or -n)   Number of mpi tasks used.\t\n                                    (required)\n     -nx <number>                   number of lons \n                                    (optional, default is 320)\n     -ny <number>                   number of lats\n                                    (optional, default is 384)\n     -res <resolution>    (or -r)   Horizontal resolution \n                                    (optional, default gx1v6)\n     -thrds <number>      (or -t)   Number of threads per mpi task\n                                    (optional, default 1)\n     -output <type>\t  (or -o)   Either output: all, maxblocks, bsize-x, bsize-y, or decomptype\n\t\t\t            (optional, default all)\n\nEXAMPLES\n\n   generate_cice_decomp.pl -res gx1v6 -nx 320 -ny 384  -nproc 80 -output maxblocks\n\n   will return a single value -- the optimum max number of blocks to utilize'' from dir '/g/g14/pochedls/e3sm/code/maint_1_0/components/cice/bld'

This may result because the version of Python that is on my path is Python 3.5 (or maybe 3.6). I was able to fix this by changing [this line](https://github.com/E3SM-Project/E3SM/blob/master/components/cice/cime_config/buildnml#L64) to: `ntasks = int(ntasks_ice / ninst_ice)`.

I don't hit this issue using maint-1.0 (which is actually what I had intended to use, but I thought I should report this).

**Comment by brhillman** [comment] 2019-01-08 00:21
+1 here. I was just about to open a PR with this fix, unless someone else is planning to fix this. FWIW, it looks like this isn't a problem with the current version of the code on the ESCOMP/CESM_CICE5 repo, so maybe this will be fixed in a future merge? It's been a minor annoyance for a while that I have to `module load` a specific python version before building or running the model.

**Comment by rljacob** [comment] 2019-01-08 04:34
@brhillman we don't pull in anything for cice so you should post the fix.  It doesn't happen in maint1_0 because buildnml there is still in perl.

**Comment by brhillman** [comment] 2019-01-08 15:52
@rljacob it is in master, yes. All that is needed to reproduce is to run `create_newcase` and then `./case.setup` using a python3 version. For me it happens when a python3 is in my path and I don't explicitly `module load` a python2.7.9 environment. I think the last time I brought up this issue it was identified as not a CIME issue but the responsibility of the CICE component, since it's occurring in the CICE buildnml script. Putting together the PR now.

**Closed** 2019-01-08 19:54 UTC
Labels: CIME, Sea Ice, bug
