### ISSUE TITLE
Build system fails on compy for some  theta integration tests

### ISSUE THREAD

**Issue by rljacob** [E3SM-Project/E3SM#3523] opened 2020-03-29 21:29 UTC
Starting on March 12, several theta tests in e3sm_integration_next started to fail to build on compy.   This was after merging both #3483 and #3418

Then on March 28, they started to pass again after integration of #3486 

The tests were:
ERS.ne4_ne4.FC5AV1C-L.compy_pgi.cam-thetahy_ftype2
ERS.ne4_ne4.FC5AV1C-L.compy_pgi.cam-thetanh_ftype2
SMS.ne4_ne4.FC5AV1C-L.compy_pgi.cam-thetahy_ftype0
SMS.ne4_ne4.FC5AV1C-L.compy_pgi.cam-thetahy_ftype1
SMS.ne4_ne4.FC5AV1C-L.compy_pgi.cam-thetahy_ftype2
SMS.ne4_ne4.FC5AV1C-L.compy_pgi.cam-thetahy_ftype4
SMS.ne4_ne4.FC5AV1C-L.compy_pgi.cam-thetahy_sl
SMS.ne4_ne4.FC5AV1C-L.compy_pgi.cam-thetanh_ftype0
SMS.ne4_ne4.FC5AV1C-L.compy_pgi.cam-thetanh_ftype1
SMS.ne4_ne4.FC5AV1C-L.compy_pgi.cam-thetanh_ftype2
SMS.ne4_ne4.FC5AV1C-L.compy_pgi.cam-thetanh_ftype4
SMS_Ln5.ne4pg2_ne4pg2.FC5AV1C-L.compy_pgi.cam-thetahy_pg2
SMS_Ln5.ne4pg2_ne4pg2.FC5AV1C-L.compy_pgi.cam-thetahy_sl_pg2

The fails could not be reproduced when run by hand individually.

**Comment by rljacob** [comment] 2020-03-29 21:31
Copying note by @ambrad from Slack

oksana and i looked at this some more tonight. i'm puzzled but want to report some observations:
Set up:
  ```
srun -p short --pty --nodes=1 --time=02:00:00 /bin/bash
  cd /compyfs/e3smtest/e3sm_scratch/ERS.ne4_ne4.FC5AV1C-L.compy_pgi.cam-thetanh_ftype2.C.JNextIntegration20200327_001517/bld/cmake-bld/cmake/lnd
  . /compyfs/e3smtest/e3sm_scratch/J/ERS.ne4_ne4.FC5AV1C-L.compy_pgi.cam-thetanh_ftype2.C.JNextIntegration20200327_001517/.env_mach_specific.sh
```
Try:
```
  make clean; make -j40 # fails
  make clean; make -j8 # fails
  make clean; make # fails
```
Failure mode is something like:
```
/qfs/projects/ops/rh7/apps/cmake/3.11.4/bin/cmake -E cmake_copy_f90_mod cmake/lnd/externalmodelinterfacemod cmake/lnd/CMakeFiles/lnd.dir/externalmodelinterfacemod.mod.stamp PGI
/qfs/projects/ops/rh7/apps/cmake/3.11.4/bin/cmake -E touch cmake/lnd/CMakeFiles/lnd.dir/__/__/clm/src/external_models/emi/src/emi/ExternalModelInterfaceMod.F90.o.provides.build
make[2]: *** [cmake/lnd/CMakeFiles/lnd.dir/__/__/clm/src/external_models/emi/src/emi/ExternalModelInterfaceMod.F90.o.provides.build] Error 1
```
And after it fails, make won't then continue; it keeps failing.
Next, I tried removing the .provides.build files, which `make clean` leaves, to get a cleaner state. Perhaps by chance, this time
`  make clean; make -j40`
succeeded. I did the obvious and ran make clean, rm'ed the .provides.build files, and make -j40 again, and it succeeded again. This is in contrast to the sequence of failures above. Thus, a tangential issue seems to be that when diagnosing issues like this, removing the .provides.build files may be necessary.
Separately, I ran 'make help > help.txt' in a different test's lnd.dir -- another ne4_ne4 test, but this using preqx -- and diff'ed it against this one's help.txt file. They are identical, as expected, so all the targets are the same.
So there's something amiss in the build system that is causing nondeterministic build errors, either in cmake itself or in our use of it, but I don't know what. I'm guessing PGI has something to do with it. I suspect that the association with theta is a red herring.

**Comment by rljacob** [comment] 2020-03-29 21:36
I don't think its PGI related.  I found the same build issues (complaints about missing modules in land files when building theta cases) when running the e3sm_integration suite with intel on compy.   It does seem to be a compy problem.  Maybe its version of cmake?

**Comment by singhbalwinder** [comment] 2020-03-30 02:05
Not sure if it is related but I have seen these kind of errors where moving the "use" statement to the top of the module (from within the subroutine) fixes the error. @jgfouca told me about this solution a while ago. As far I remember, we had to do that at one or two places under cam.

**Comment by jgfouca** [comment] 2020-03-30 17:05
Looking at it now.

**Comment by jgfouca** [comment] 2020-03-31 16:52
I was also unable to get any build errors to repeat:

```
% ./create_test eam_theta --no-run --compiler=pgi
...
PASS ERS.ne4_ne4.FC5AV1C-L.compy_pgi.cam-thetanh_ftype2 MODEL_BUILD
    Case dir: /compyfs/fouc928/e3sm_scratch/ERS.ne4_ne4.FC5AV1C-L.compy_pgi.cam-thetanh_ftype2.20200331_092555_a96i8c
PASS ERS.ne4_ne4.FC5AV1C-L.compy_pgi.cam-thetahy_ftype2 MODEL_BUILD
    Case dir: /compyfs/fouc928/e3sm_scratch/ERS.ne4_ne4.FC5AV1C-L.compy_pgi.cam-thetahy_ftype2.20200331_092555_a96i8c
PASS SMS.ne4_ne4.FC5AV1C-L.compy_pgi.cam-thetanh_ftype4 MODEL_BUILD
    Case dir: /compyfs/fouc928/e3sm_scratch/SMS.ne4_ne4.FC5AV1C-L.compy_pgi.cam-thetanh_ftype4.20200331_092555_a96i8c
PASS SMS.ne4_ne4.FC5AV1C-L.compy_pgi.cam-thetanh_ftype1 MODEL_BUILD
    Case dir: /compyfs/fouc928/e3sm_scratch/SMS.ne4_ne4.FC5AV1C-L.compy_pgi.cam-thetanh_ftype1.20200331_092555_a96i8c
PASS SMS.ne4_ne4.FC5AV1C-L.compy_pgi.cam-thetanh_ftype0 MODEL_BUILD
    Case dir: /compyfs/fouc928/e3sm_scratch/SMS.ne4_ne4.FC5AV1C-L.compy_pgi.cam-thetanh_ftype0.20200331_092555_a96i8c
PASS SMS.ne4_ne4.FC5AV1C-L.compy_pgi.cam-thetanh_ftype2 MODEL_BUILD
    Case dir: /compyfs/fouc928/e3sm_scratch/SMS.ne4_ne4.FC5AV1C-L.compy_pgi.cam-thetanh_ftype2.20200331_092555_a96i8c
PASS SMS.ne4_ne4.FC5AV1C-L.compy_pgi.cam-thetahy_ftype0 MODEL_BUILD
    Case dir: /compyfs/fouc928/e3sm_scratch/SMS.ne4_ne4.FC5AV1C-L.compy_pgi.cam-thetahy_ftype0.20200331_092555_a96i8c
PASS SMS.ne4_ne4.FC5AV1C-L.compy_pgi.cam-thetahy_ftype2 MODEL_BUILD
    Case dir: /compyfs/fouc928/e3sm_scratch/SMS.ne4_ne4.FC5AV1C-L.compy_pgi.cam-thetahy_ftype2.20200331_092555_a96i8c
PASS SMS.ne4_ne4.FC5AV1C-L.compy_pgi.cam-thetahy_ftype4 MODEL_BUILD
    Case dir: /compyfs/fouc928/e3sm_scratch/SMS.ne4_ne4.FC5AV1C-L.compy_pgi.cam-thetahy_ftype4.20200331_092555_a96i8c
PASS SMS.ne4_ne4.FC5AV1C-L.compy_pgi.cam-thetahy_sl MODEL_BUILD
    Case dir: /compyfs/fouc928/e3sm_scratch/SMS.ne4_ne4.FC5AV1C-L.compy_pgi.cam-thetahy_sl.20200331_092555_a96i8c
PASS SMS.ne4_ne4.FC5AV1C-L.compy_pgi.cam-thetahy_ftype1 MODEL_BUILD
    Case dir: /compyfs/fouc928/e3sm_scratch/SMS.ne4_ne4.FC5AV1C-L.compy_pgi.cam-thetahy_ftype1.20200331_092555_a96i8c
```

**Comment by jgfouca** [comment] 2020-03-31 16:53
I will try again with an older commit.

**Comment by singhbalwinder** [comment] 2020-03-31 17:30
Are you using master branch? I am debugging another issue which only appears in next. You might want to try next branch (although debugging next may not be useful as it is a throwaway branch).

**Comment by jgfouca** [comment] 2020-03-31 17:45
@singhbalwinder , yes; my first try was latest master.

I'm trying pre-#3486 now. I will try next too.

**Comment by jgfouca** [comment] 2020-03-31 19:21
@singhbalwinder , next seemed to work fine.

@rljacob , pre-#3486 worked fine.

**Comment by cameronsmith1** [comment] 2020-04-02 08:58
@ndkeen also had some problems and identified a solution with @jonbob, as discussed in https://github.com/E3SM-Project/E3SM/issues/3528.  Could this be causing your issues too?

**Comment by jgfouca** [comment] 2020-04-04 18:13
I was not able to reproduce this error. Closing until someone is able to provide a reproducible use case.

**Closed by jgfouca** 2020-04-04 18:13 UTC
Labels: CIME, Compy, PotentialBug, Testing
